source(file.path("..", "..", "report_components.R"))

.write_file <- function(path, lines = "x") {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, path)
}

.write_json <- function(path, object) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  jsonlite::write_json(
    object,
    path = path,
    auto_unbox = TRUE,
    pretty = TRUE,
    null = "null"
  )
}

.create_fake_repo <- function(root, version = "3.3.1") {
  dir.create(file.path(root, "docs"), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(root, "tools"), recursive = TRUE, showWarnings = FALSE)
  .write_file(file.path(root, "DESCRIPTION"), "Package: fake")
  .write_file(
    file.path(root, "inst", "extdata", "webawesome", "VERSION"),
    version
  )
  .write_file(
    file.path(root, "NAMESPACE"),
    c(
      "export(update_wa_select)",
      "export(wa_button)",
      "export(wa_page)",
      "export(wa_select)"
    )
  )
  .write_file(
    file.path(root, "R", "wa_warning_registry.R"),
    c(
      ".wa_warning_defaults <- function() {",
      "  list()",
      "}",
      "",
      ".wa_warning_keys <- function() {",
      "  names(.wa_warning_defaults())",
      "}"
    )
  )
  .write_file(
    file.path(root, "R", "wa_page.R"),
    c(
      "#' Manual helper.",
      "#' @export",
      "wa_page <- function(...) NULL"
    )
  )
  .write_file(
    file.path(root, "dev", "generation", "binding-overrides.yaml"),
    c(
      "schema_version: 1",
      "",
      "components:",
      "  - tag: wa-button",
      "    binding:",
      "      mode: action",
      "      event: click",
      "      rationale: Button should act like a Shiny action input."
    )
  )
  .write_file(
    file.path(root, "dev", "manifests", "component-coverage.policy.yaml"),
    c(
      "schema_version: 1",
      "",
      "components: []"
    )
  )
}

.fake_custom_elements <- function() {
  list(
    schemaVersion = "1.0.0",
    package = list(name = "@awesome.me/webawesome"),
    modules = list(
      list(
        path = "components/button/button.js",
        declarations = list(
          list(
            kind = "class",
            name = "WaButton",
            tagName = "wa-button",
            attributes = list(
              list(
                name = "appearance",
                fieldName = "appearance",
                type = list(text = "'filled' | 'outlined'")
              )
            ),
            members = list(
              list(
                name = "appearance",
                kind = "field",
                type = list(text = "'filled' | 'outlined'")
              )
            )
          )
        )
      ),
      list(
        path = "components/form/select.js",
        declarations = list(
          list(
            kind = "class",
            name = "WaSelect",
            tagName = "wa-select",
            attributes = list(
              list(
                name = "placeholder",
                fieldName = "placeholder",
                type = list(text = "string")
              ),
              list(
                name = "multiple",
                fieldName = "multiple",
                type = list(text = "boolean")
              ),
              list(
                name = "value",
                fieldName = "value",
                type = list(text = "string")
              ),
              list(
                name = "with-clear",
                fieldName = "withClear",
                type = list(text = "boolean")
              )
            ),
            members = list(
              list(
                name = "value",
                kind = "field",
                type = list(text = "string")
              ),
              list(
                name = "withClear",
                kind = "field",
                type = list(text = "boolean")
              )
            ),
            events = list(
              list(
                name = "wa-change",
                type = list(text = "CustomEvent<string>")
              ),
              list(name = "wa-input", type = list(text = "CustomEvent<string>"))
            )
          )
        )
      )
    )
  )
}

.create_generated_surface <- function(root) {
  .write_json(
    file.path(root, "inst", "extdata", "webawesome", "custom-elements.json"),
    .fake_custom_elements()
  )
  .write_file(
    file.path(root, "R", "wa_button.R"),
    c(
      "# Generated by tools/generate_components.R. Do not edit by hand.",
      "",
      "wa_button <- function(",
      "  input_id,",
      "  ...,",
      "  appearance = NULL",
      ") NULL"
    )
  )
  .write_file(
    file.path(root, "R", "wa_select.R"),
    c(
      "# Generated by tools/generate_components.R. Do not edit by hand.",
      "",
      "wa_select <- function(",
      "  input_id,",
      "  ...,",
      "  value = NULL,",
      "  multiple = NULL,",
      "  placeholder = NULL,",
      "  with_clear = NULL",
      ") NULL",
      "",
      "update_wa_select <- function(",
      "  session,",
      "  input_id,",
      "  value = NULL",
      ") NULL"
    )
  )
  .write_file(
    file.path(root, "R", "wa_stale.R"),
    c(
      "# Generated by tools/generate_components.R. Do not edit by hand.",
      "",
      "wa_stale <- function(...) NULL"
    )
  )
  .write_file(
    file.path(root, "inst", "bindings", "wa_select.js"),
    c(
      "// # Generated by tools/generate_components.R. Do not edit by hand.",
      "",
      "const binding = new Shiny.InputBinding();",
      "",
      "$.extend(binding, {",
      "  find(scope) {",
      "    return $(scope).find('wa-select[id]');",
      "  },",
      "  getId(el) {",
      "    return el.id;",
      "  },",
      "  getValue(el) {",
      "    return el.value;",
      "  },",
      "  subscribe(el, callback) {",
      "    el.__shinyWebawesomeCallback = () => callback();",
      "    el.__shinyWebawesomeEvents = [\"wa-change\"];",
      "    el.__shinyWebawesomeEvents.forEach((eventName) => {",
      "      el.addEventListener(eventName, el.__shinyWebawesomeCallback);",
      "    });",
      "  },",
      "  unsubscribe(el, callback) {",
      "    if (el.__shinyWebawesomeCallback) {",
      "      (el.__shinyWebawesomeEvents || []).forEach((eventName) => {",
      paste0(
        "        el.removeEventListener(",
        "eventName, el.__shinyWebawesomeCallback);"
      ),
      "      });",
      "      delete el.__shinyWebawesomeEvents;",
      "      delete el.__shinyWebawesomeCallback;",
      "    }",
      "  },",
      "  receiveMessage(el, data) {",
      paste0(
        "    if (Object.prototype.hasOwnProperty.call(data, ",
        "\"value\")) { el.value = data.value; }"
      ),
      "    el.dispatchEvent(new Event('change', { bubbles: true }));",
      "  }",
      "});",
      "",
      "Shiny.inputBindings.register(binding, 'shiny.webawesome.wa_select');"
    )
  )
  .write_file(
    file.path(root, "inst", "bindings", "wa_button.js"),
    c(
      "// # Generated by tools/generate_components.R. Do not edit by hand.",
      "",
      "const binding = new Shiny.InputBinding();",
      "",
      "$.extend(binding, {",
      "  find(scope) {",
      "    return $(scope).find('wa-button[id]');",
      "  },",
      "  getId(el) {",
      "    return el.id;",
      "  },",
      "  getValue(el) {",
      "    return $(el).data(\"val\") || 0;",
      "  },",
      "  getType(el) {",
      "    return \"shiny.action\";",
      "  },",
      "  subscribe(el, callback) {",
      "    el.__shinyWebawesomeCallback = () => {",
      "      const val = $(el).data(\"val\") || 0;",
      "      $(el).data(\"val\", val + 1);",
      "      callback(false);",
      "    };",
      "    el.__shinyWebawesomeEvents = [\"click\"];",
      "    el.__shinyWebawesomeEvents.forEach((eventName) => {",
      "      el.addEventListener(eventName, el.__shinyWebawesomeCallback);",
      "    });",
      "  },",
      "  unsubscribe(el, callback) {",
      "    if (el.__shinyWebawesomeCallback) {",
      "      (el.__shinyWebawesomeEvents || []).forEach((eventName) => {",
      paste0(
        "        el.removeEventListener(",
        "eventName, el.__shinyWebawesomeCallback);"
      ),
      "      });",
      "      delete el.__shinyWebawesomeEvents;",
      "      delete el.__shinyWebawesomeCallback;",
      "    }",
      "  },",
      "  receiveMessage(el, data) {",
      "    if (Object.prototype.hasOwnProperty.call(data, \"disabled\")) {",
      "      if (data.disabled) {",
      "        el.setAttribute(\"disabled\", \"\");",
      "      } else {",
      "        el.removeAttribute(\"disabled\");",
      "      }",
      "    }",
      "  }",
      "});",
      "",
      "Shiny.inputBindings.register(binding, 'shiny.webawesome.wa_button');"
    )
  )
}

.create_nonconformant_surface <- function(root) {
  .create_generated_surface(root)
  .write_file(
    file.path(root, "R", "wa_select.R"),
    c(
      "# Generated by tools/generate_components.R. Do not edit by hand.",
      "",
      "wa_select <- function(input_id, ..., value = NULL) NULL",
      "",
      "update_wa_select <- function(session, input_id, value = NULL) NULL"
    )
  )
}

testthat::test_that(
  "report_components writes deterministic manifests and reports",
  {
    root <- withr::local_tempdir()
    .create_fake_repo(root)
    .create_generated_surface(root)

    result <- report_components(root = root, verbose = FALSE)

    testthat::expect_true(file.exists(file.path(
      root, "manifests", "generated-file-manifest.yaml"
    )))
    testthat::expect_true(file.exists(file.path(
      root, "manifests", "component-coverage.yaml"
    )))
    testthat::expect_true(file.exists(file.path(
      root, "manifests", "component-api-conformance.yaml"
    )))
    testthat::expect_true(file.exists(file.path(
      root, "manifests", "manual-api-inventory.yaml"
    )))
    testthat::expect_true(file.exists(file.path(root, "report", "summary.md")))
    testthat::expect_true(file.exists(file.path(
      root, "report", "generated-files.md"
    )))
    testthat::expect_true(file.exists(file.path(
      root, "report", "component-coverage.md"
    )))
    testthat::expect_true(file.exists(file.path(
      root, "report", "component-api-conformance.md"
    )))
    testthat::expect_true(file.exists(file.path(
      root, "report", "manual-api-inventory.md"
    )))

    testthat::expect_equal(result$generated_file_manifest$summary$expected, 4)
    testthat::expect_equal(
      result$generated_file_manifest$summary$unexpected,
      1
    )
    testthat::expect_equal(
      result$component_coverage_manifest$summary$covered,
      2
    )
    testthat::expect_equal(
      result$manual_api_inventory$summary$manual_exports,
      1
    )
    testthat::expect_equal(
      result$component_api_conformance$summary$nonconformant,
      0
    )
    testthat::expect_true(
      result$component_api_conformance$components[[1]]$wrapper$args_match
    )

    select_entry <- result$component_api_conformance$components[[2]]
    testthat::expect_true(select_entry$wrapper$args_match)
    testthat::expect_true(select_entry$binding$events_match)
    testthat::expect_true(select_entry$update_function$args_match)

    manual_inventory <- yaml::read_yaml(
      file.path(root, "manifests", "manual-api-inventory.yaml")
    )
    testthat::expect_equal(manual_inventory$summary$manual_exports, 1)
    testthat::expect_equal(manual_inventory$exports[[1]]$name, "wa_page")

    generated_files_report <- readLines(
      file.path(root, "report", "generated-files.md"),
      warn = FALSE
    )
    testthat::expect_true(any(grepl(
      "wa_stale.R",
      generated_files_report,
      fixed = TRUE
    )))
  }
)

testthat::test_that("report_components detects deeper conformance drift", {
  root <- withr::local_tempdir()
  .create_fake_repo(root)
  .create_nonconformant_surface(root)

  result <- report_components(root = root, verbose = FALSE)

  testthat::expect_gte(
    result$component_api_conformance$summary$nonconformant,
    1
  )

  select_entry <- result$component_api_conformance$components[[2]]
  testthat::expect_false(select_entry$wrapper$args_match)
  testthat::expect_true(length(select_entry$wrapper$missing_args) > 0L)
})
