source(file.path("..", "..", "publish.R"))

# nolint start: object_usage_linter
.write_file <- function(path, lines = "x") {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, path)
}

.create_fake_repo <- function(root) {
  dir.create(
    file.path(root, "projectdocs"),
    recursive = TRUE,
    showWarnings = FALSE
  )
  dir.create(file.path(root, "tools"), recursive = TRUE, showWarnings = FALSE)

  .write_file(file.path(root, "DESCRIPTION"), c(
    "Package: fake",
    "Version: 0.1.0"
  ))
  .write_file(file.path(root, "NEWS.md"), "# Version 0.1.0")
  .write_file(file.path(root, "projectdocs", "README.md"), "docs")
  .write_file(file.path(root, "website", "index.html"), "<html></html>")
  .write_file(file.path(root, "fake_0.1.0.tar.gz"), "tarball")
}

.fake_git_runner <- function(branch = "main",
                             clean = TRUE,
                             local_tag = FALSE,
                             remote_tag = FALSE,
                             log = NULL) {
  force(branch)
  force(clean)
  force(local_tag)
  force(remote_tag)
  force(log)

  function(command, args = character(), wd = ".", env = character()) {
    if (!is.null(log)) {
      log$calls <- c(
        log$calls,
        list(list(command = command, args = args, wd = wd))
      )
    }

    if (identical(command, "git") && identical(args, c("rev-parse", "HEAD"))) {
      return(list(status = 0L, stdout = "abc123", stderr = character()))
    }

    if (
      identical(command, "git") &&
        identical(args, c("rev-parse", "--abbrev-ref", "HEAD"))
    ) {
      return(list(status = 0L, stdout = branch, stderr = character()))
    }

    if (
      identical(command, "git") &&
        identical(args, c("status", "--porcelain"))
    ) {
      stdout <- if (isTRUE(clean)) "" else " M DESCRIPTION"
      return(list(status = 0L, stdout = stdout, stderr = character()))
    }

    if (identical(command, "git") && identical(args, "ls-files")) {
      return(list(
        status = 0L,
        stdout = c("DESCRIPTION\nNEWS.md\nprojectdocs/README.md"),
        stderr = character()
      ))
    }

    if (
      identical(command, "git") &&
        length(args) >= 2L &&
        identical(args[[1]], "tag") &&
        identical(args[[2]], "--list")
    ) {
      stdout <- if (isTRUE(local_tag)) args[[3]] else ""
      return(list(status = 0L, stdout = stdout, stderr = character()))
    }

    if (
      identical(command, "git") &&
        identical(
          args[seq_len(4)],
          c("ls-remote", "--tags", "--refs", "origin")
        )
    ) {
      stdout <- if (isTRUE(remote_tag)) "abc123\trefs/tags/0.1.0" else ""
      return(list(status = 0L, stdout = stdout, stderr = character()))
    }

    if (
      identical(command, "git") &&
        (
          identical(args, c("tag", "0.1.0")) ||
            identical(args, c("push", "origin", branch)) ||
            identical(args, c("push", "origin", "refs/tags/0.1.0"))
        )
    ) {
      return(list(status = 0L, stdout = character(), stderr = character()))
    }

    list(status = 0L, stdout = character(), stderr = character())
  }
}

.write_finalize_handoff <- function(root,
                                    mode = "strict",
                                    status = "pass",
                                    warnings = list()) {
  tracked_tree <- .tracked_tree_record(root, runner = .fake_git_runner())
  website_tree <- .website_tree_record(root)
  tarball_path <- file.path(root, "fake_0.1.0.tar.gz")

  handoff <- list(
    schema_version = 1L,
    record_type = "finalize_handoff",
    generated_at = .integrity_timestamp(),
    status = status,
    mode = mode,
    package_version = "0.1.0",
    git_head = "abc123",
    warnings = warnings,
    artifacts = list(
      tarball = list(
        path = tarball_path,
        digest = .file_sha256(tarball_path)
      ),
      website = list(
        path = "website",
        file_count = website_tree$summary$file_count,
        tree_digest = website_tree$summary$tree_digest
      ),
      tracked_tree = list(
        file_count = tracked_tree$summary$file_count,
        tree_digest = tracked_tree$summary$tree_digest
      )
    )
  )

  dir.create(file.path(root, "manifests", "finalize"), recursive = TRUE)
  writeLines(
    c(
      "# Generated by tools/finalize_package.R. Do not edit by hand.",
      yaml::as.yaml(
        handoff,
        indent.mapping.sequence = TRUE,
        line.sep = "\n"
      )
    ),
    file.path(root, "manifests", "finalize", "release-handoff.yaml")
  )
}

testthat::test_that(
  "publish_package dry-run writes artifacts and records readiness warnings",
  {
    testthat::skip_if_not_installed("digest")
    testthat::skip_if_not_installed("yaml")

    root <- withr::local_tempdir()
    .create_fake_repo(root)
    .write_finalize_handoff(
      root,
      mode = "default",
      status = "warn",
      warnings = list(confirmations = "Visual review not yet confirmed.")
    )

    result <- publish_package(
      release_version = "0.1.0",
      root = root,
      dry_run = TRUE,
      verbose = FALSE,
      runner = .fake_git_runner(branch = "feature/release")
    )

    testthat::expect_true(
      file.exists(
        file.path(root, "manifests", "publish", "release-publish.yaml")
      )
    )
    testthat::expect_true(
      file.exists(file.path(root, "reports", "publish", "summary.md"))
    )
    testthat::expect_equal(result$record$status, "warn")
    testthat::expect_match(
      result$warnings$handoff_mode,
      "not strict"
    )
    testthat::expect_match(
      result$warnings$branch,
      "not `main`"
    )
    testthat::expect_false(isTRUE(result$executed_actions$do_tag))
    testthat::expect_false(isTRUE(result$executed_actions$deploy_site))
  }
)

testthat::test_that(
  paste(
    "publish_package executes requested tag and deploy actions",
    "after verification"
  ),
  {
    testthat::skip_if_not_installed("digest")
    testthat::skip_if_not_installed("yaml")

    root <- withr::local_tempdir()
    .create_fake_repo(root)
    .write_finalize_handoff(root)

    call_log <- new.env(parent = emptyenv())
    call_log$calls <- list()
    deploy_log <- new.env(parent = emptyenv())
    deploy_log$called <- FALSE

    result <- publish_package(
      release_version = "0.1.0",
      root = root,
      do_tag = TRUE,
      deploy_site = TRUE,
      verbose = FALSE,
      runner = .fake_git_runner(log = call_log),
      deployer = function(root, dry_run = FALSE, runner = NULL) {
        deploy_log$called <- TRUE
        testthat::expect_false(isTRUE(dry_run))
        invisible(TRUE)
      }
    )

    command_args <- lapply(call_log$calls, function(call) call$args)

    testthat::expect_equal(result$record$status, "pass")
    testthat::expect_true(isTRUE(result$executed_actions$do_tag))
    testthat::expect_true(isTRUE(result$executed_actions$deploy_site))
    testthat::expect_true(isTRUE(deploy_log$called))
    testthat::expect_true(any(vapply(
      command_args,
      identical,
      logical(1),
      c("tag", "0.1.0")
    )))
    testthat::expect_true(any(vapply(
      command_args,
      identical,
      logical(1),
      c("push", "origin", "main")
    )))
    testthat::expect_true(any(vapply(
      command_args,
      identical,
      logical(1),
      c("push", "origin", "refs/tags/0.1.0")
    )))
  }
)

testthat::test_that(
  "publish_package removes stale publish artifacts before a new run",
  {
    testthat::skip_if_not_installed("digest")
    testthat::skip_if_not_installed("yaml")

    root <- withr::local_tempdir()
    .create_fake_repo(root)
    .write_finalize_handoff(root)

    .write_file(
      file.path(root, "manifests", "publish", "release-publish.yaml"),
      "stale"
    )
    .write_file(file.path(root, "reports", "publish", "summary.md"), "stale")

    result <- publish_package(
      release_version = "0.1.0",
      root = root,
      dry_run = TRUE,
      verbose = FALSE,
      runner = .fake_git_runner()
    )

    testthat::expect_true(
      "manifests/publish/release-publish.yaml" %in%
        result$record$removed_outputs
    )
    testthat::expect_true(
      "reports/publish/summary.md" %in% result$record$removed_outputs
    )
  }
)
# nolint end: object_usage_linter
