.write_file <- function(path, lines = "x") {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, path)
}

.write_json <- function(path, object) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  jsonlite::write_json(
    object,
    path = path,
    auto_unbox = TRUE,
    pretty = TRUE,
    null = "null"
  )
}

.copy_report_tool <- function(root) {
  dir.create(
    file.path(root, "tools", "generate"),
    recursive = TRUE,
    showWarnings = FALSE
  )
  file.copy(
    normalizePath(
      file.path("..", "..", "report_components.R"),
      mustWork = TRUE
    ),
    file.path(root, "tools", "report_components.R")
  )
  file.copy(
    normalizePath(file.path("..", "..", "cli_ui.R"), mustWork = TRUE),
    file.path(root, "tools", "cli_ui.R")
  )
  file.copy(
    normalizePath(file.path("..", "..", "integrity.R"), mustWork = TRUE),
    file.path(root, "tools", "integrity.R")
  )

  helper_files <- c(
    "utils.R",
    "policy.R",
    "metadata.R",
    "schema.R",
    "render_utils.R",
    "render_wrappers.R",
    "render_updates.R",
    "render_bindings.R"
  )
  for (file in helper_files) {
    file.copy(
      normalizePath(file.path("..", "..", "generate", file), mustWork = TRUE),
      file.path(root, "tools", "generate", file)
    )
  }

  Sys.chmod(file.path(root, "tools", "report_components.R"), mode = "0755")
}

.create_fake_repo <- function(root) {
  dir.create(file.path(root, "docs"), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(root, "tools"), recursive = TRUE, showWarnings = FALSE)
  .write_file(file.path(root, "DESCRIPTION"), "Package: fake")
  .write_file(
    file.path(root, "inst", "extdata", "webawesome", "VERSION"),
    "3.3.1"
  )
  .write_file(
    file.path(root, "NAMESPACE"),
    c(
      "export(update_wa_select)",
      "export(wa_select)"
    )
  )
  .write_file(
    file.path(root, "R", "wa_warning_registry.R"),
    c(
      ".wa_warning_defaults <- function() {",
      "  list()",
      "}",
      "",
      ".wa_warning_keys <- function() {",
      "  names(.wa_warning_defaults())",
      "}"
    )
  )
  .write_file(
    file.path(root, "R", "wa_select.R"),
    c(
      "# Generated by tools/generate_components.R. Do not edit by hand.",
      "",
      "wa_select <- function(...) NULL",
      "",
      "update_wa_select <- function(...) NULL"
    )
  )
  .write_file(
    file.path(root, "inst", "bindings", "wa_select.js"),
    "export default {};"
  )
  .write_json(
    file.path(root, "inst", "extdata", "webawesome", "custom-elements.json"),
    list(
      schemaVersion = "1.0.0",
      package = list(name = "@awesome.me/webawesome"),
      modules = list(
        list(
          path = "components/form/select.js",
          declarations = list(
            list(
              kind = "class",
              name = "WaSelect",
              tagName = "wa-select",
              attributes = list(
                list(
                  name = "placeholder",
                  fieldName = "placeholder",
                  type = list(text = "string")
                ),
                list(
                  name = "multiple",
                  fieldName = "multiple",
                  type = list(text = "boolean")
                ),
                list(
                  name = "value",
                  fieldName = "value",
                  type = list(text = "string")
                ),
                list(
                  name = "with-clear",
                  fieldName = "withClear",
                  type = list(text = "boolean")
                )
              ),
              members = list(
                list(
                  name = "value",
                  kind = "field",
                  type = list(text = "string")
                ),
                list(
                  name = "withClear",
                  kind = "field",
                  type = list(text = "boolean")
                )
              ),
              events = list(
                list(
                  name = "wa-change",
                  type = list(text = "CustomEvent<string>")
                )
              )
            )
          )
        )
      )
    )
  )
  .write_file(
    file.path(root, "dev", "manifests", "component-coverage.policy.yaml"),
    c(
      "schema_version: 1",
      "",
      "components: []"
    )
  )

  .copy_report_tool(root)
}

.run_report_script <- function(root, args = character()) {
  processx::run(
    command = "./tools/report_components.R",
    args = args,
    wd = root,
    echo = FALSE,
    error_on_status = FALSE
  )
}

testthat::test_that("report_components CLI prints help", {
  root <- withr::local_tempdir()
  .create_fake_repo(root)

  result <- .run_report_script(root, "--help")

  testthat::expect_equal(result$status, 0)
  testthat::expect_match(result$stdout, "Usage: ./tools/report_components.R")
  testthat::expect_match(result$stdout, "--quiet")
})

testthat::test_that("report_components CLI writes manifests and reports", {
  root <- withr::local_tempdir()
  .create_fake_repo(root)

  result <- .run_report_script(root)

  testthat::expect_equal(result$status, 0)
  testthat::expect_match(result$stderr, "Generating reports \\.{2,} Done")
  testthat::expect_true(file.exists(file.path(
    root, "manifests", "component-coverage.yaml"
  )))
  testthat::expect_true(file.exists(file.path(root, "report", "summary.md")))
})
