# Shared integrity helpers for the shiny.webawesome build pipeline.
#
# This file is sourced by build-stage scripts under tools/. It is not package
# runtime code.

# Return one fallback value when the first argument is NULL.
.or_default <- function(x, y) {
  if (is.null(x)) {
    y
  } else {
    x
  }
}

# Return the generated-file marker used by the component generator.
.generated_file_marker <- function() {
  "# Generated by tools/generate_components.R. Do not edit by hand."
}

# Return the directory containing generated integrity records.
.integrity_dir <- function(root) {
  file.path(root, "manifests", "integrity")
}

# Return the prune integrity record path.
.prune_integrity_record_path <- function(root) {
  file.path(.integrity_dir(root), "prune-output.yaml")
}

# Return the generate integrity record path.
.generate_record_path <- function(root) {
  file.path(.integrity_dir(root), "generate-output.yaml")
}

# Return one relative path with the repository root removed.
.strip_root_prefix <- function(paths, root) {
  sub(paste0("^", root, "/?"), "", paths)
}

# List deterministic relative files under one repository-local directory.
.integrity_list_relative_files <- function(root, rel_dir) {
  abs_dir <- file.path(root, rel_dir)
  if (!dir.exists(abs_dir)) {
    return(character())
  }

  files <- list.files(
    abs_dir,
    recursive = TRUE,
    all.files = FALSE,
    no.. = TRUE,
    full.names = TRUE
  )

  if (length(files) == 0L) {
    return(character())
  }

  files <- files[file.info(files)$isdir %in% FALSE]
  sort(.strip_root_prefix(files, root))
}

# Return sorted top-level generated R files owned by generate_components().
.generated_r_files <- function(root) {
  r_dir <- file.path(root, "R")
  if (!dir.exists(r_dir)) {
    return(character())
  }

  paths <- list.files(r_dir, pattern = "\\.[Rr]$", full.names = TRUE)
  if (length(paths) == 0L) {
    return(character())
  }

  owned <- vapply(
    paths,
    function(path) {
      lines <- readLines(path, n = 1L, warn = FALSE)
      length(lines) > 0L && identical(lines[[1]], .generated_file_marker())
    },
    logical(1)
  )

  sort(paths[owned])
}

# Return sorted generated binding files.
.generated_binding_files <- function(root) {
  binding_dir <- file.path(root, "inst", "bindings")
  if (!dir.exists(binding_dir)) {
    return(character())
  }

  sort(list.files(binding_dir, pattern = "\\.js$", full.names = TRUE))
}

# Return the current relative prune-owned output files.
.prune_integrity_surface_files <- function(root) {
  sort(c(
    .integrity_list_relative_files(
      root,
      file.path("inst", "extdata", "webawesome")
    ),
    .integrity_list_relative_files(root, file.path("inst", "www", "wa"))
  ))
}

# Return the current relative generate-owned output files.
.generate_surface_files <- function(root) {
  wrappers <- .generated_r_files(root)
  bindings <- .generated_binding_files(root)
  sort(c(
    .strip_root_prefix(wrappers, root),
    .strip_root_prefix(bindings, root)
  ))
}

# Return one normalized UTC timestamp string for integrity records.
.integrity_timestamp <- function(time = Sys.time()) {
  format(as.POSIXct(time, tz = "UTC"), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
}

# Return one sha256 digest string for a file.
.file_sha256 <- function(path) {
  if (!requireNamespace("digest", quietly = TRUE)) {
    stop(
      "The `digest` package is required to compute integrity records.",
      call. = FALSE
    )
  }

  paste0(
    "sha256:",
    digest::digest(file = path, algo = "sha256", serialize = FALSE)
  )
}

# Return one sha256 digest string for arbitrary text.
.text_sha256 <- function(text) {
  if (!requireNamespace("digest", quietly = TRUE)) {
    stop(
      "The `digest` package is required to compute integrity records.",
      call. = FALSE
    )
  }

  paste0(
    "sha256:",
    digest::digest(text, algo = "sha256", serialize = FALSE)
  )
}

# Build one deterministic file-entry vector for integrity recording.
.integrity_file_entry <- function(root, relative_path) {
  absolute_path <- file.path(root, relative_path)
  info <- file.info(absolute_path)

  list(
    path = relative_path,
    size = unname(as.numeric(info$size)),
    digest = .file_sha256(absolute_path)
  )
}

# Build the deterministic tree digest input lines for one file-entry list.
.integrity_tree_digest_lines <- function(files) {
  if (length(files) == 0L) {
    return(character())
  }

  vapply(
    files,
    function(file) {
      paste(file$path, file$size, file$digest, sep = "\t")
    },
    character(1)
  )
}

# Build one integrity record for a stage-owned file surface.
.build_integrity_record <- function(root,
                                    stage,
                                    surface_name,
                                    surface_roots,
                                    relative_files) {
  files <- lapply(relative_files, .integrity_file_entry, root = root)
  tree_lines <- .integrity_tree_digest_lines(files)

  list(
    schema_version = 1L,
    record_type = "integrity_record",
    stage = stage,
    generated_at = .integrity_timestamp(),
    surface = list(
      name = surface_name,
      roots = surface_roots
    ),
    summary = list(
      file_count = length(relative_files),
      tree_digest = .text_sha256(paste(tree_lines, collapse = "\n"))
    ),
    files = files
  )
}

# Return generated-file comment preamble lines for integrity records.
.integrity_comment_preamble <- function(record) {
  c(
    "# Generated by shiny.webawesome build tooling. Do not edit by hand.",
    paste0(
      "# Integrity record for stage `",
      record$stage,
      "` and surface `",
      record$surface$name,
      "`."
    )
  )
}

# Write one integrity record as YAML with a generated-file preamble.
.write_integrity_record <- function(path, record) {
  if (!requireNamespace("yaml", quietly = TRUE)) {
    stop(
      "The `yaml` package is required to write integrity records.",
      call. = FALSE
    )
  }

  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  yaml_text <- yaml::as.yaml(
    record,
    indent.mapping.sequence = TRUE,
    line.sep = "\n"
  )
  text <- paste(
    c(.integrity_comment_preamble(record), yaml_text),
    collapse = "\n"
  )
  writeLines(enc2utf8(text), path, useBytes = TRUE)

  invisible(path)
}

# Read one integrity record when present.
.read_integrity_record <- function(path) {
  if (!file.exists(path)) {
    return(NULL)
  }

  if (!requireNamespace("yaml", quietly = TRUE)) {
    stop(
      "The `yaml` package is required to read integrity records.",
      call. = FALSE
    )
  }

  yaml::read_yaml(path)
}

# Build the current prune output integrity record.
.current_prune_record <- function(root) {
  .build_integrity_record(
    root = root,
    stage = "prune",
    surface_name = "prune_output",
    surface_roots = c("inst/extdata/webawesome", "inst/www/wa"),
    relative_files = .prune_integrity_surface_files(root)
  )
}

# Build the current generate output integrity record.
.current_generate_record <- function(root) {
  .build_integrity_record(
    root = root,
    stage = "generate",
    surface_name = "generate_output",
    surface_roots = c("R", "inst/bindings"),
    relative_files = .generate_surface_files(root)
  )
}

# Return one named character vector keyed by file path from a record.
.integrity_file_map <- function(record, field = c("digest", "size")) {
  field <- match.arg(field)
  files <- .or_default(record$files, list())

  if (length(files) == 0L) {
    return(stats::setNames(character(), character()))
  }

  stats::setNames(
    vapply(
      files,
      function(file) as.character(.or_default(file[[field]], "")),
      character(1)
    ),
    vapply(files, function(file) .or_default(file$path, ""), character(1))
  )
}

# Compare a recorded surface against the current surface.
.compare_integrity_record <- function(expected_record,
                                      current_record,
                                      expected_label,
                                      current_label) {
  if (is.null(expected_record)) {
    return(list(
      ok = FALSE,
      status = "warn",
      summary = paste0("no ", expected_label, " integrity record found"),
      details = paste0(
        "Missing integrity record for ",
        expected_label,
        ": expected prior stage output was not recorded."
      )
    ))
  }

  expected_paths <- names(
    .integrity_file_map(expected_record, field = "digest")
  )
  current_paths <- names(.integrity_file_map(current_record, field = "digest"))
  missing_paths <- setdiff(expected_paths, current_paths)
  unexpected_paths <- setdiff(current_paths, expected_paths)

  if (length(missing_paths) > 0L || length(unexpected_paths) > 0L) {
    details <- c(
      if (length(missing_paths) > 0L) {
        paste0("Missing files: ", paste(sort(missing_paths), collapse = ", "))
      },
      if (length(unexpected_paths) > 0L) {
        paste0(
          "Unexpected files: ",
          paste(sort(unexpected_paths), collapse = ", ")
        )
      }
    )

    return(list(
      ok = FALSE,
      status = "warn",
      summary = paste0("file set mismatch against ", expected_label),
      details = details
    ))
  }

  expected_digests <- .integrity_file_map(expected_record, field = "digest")
  current_digests <- .integrity_file_map(current_record, field = "digest")
  digest_mismatches <- names(expected_digests)[
    expected_digests != current_digests
  ]

  if (length(digest_mismatches) > 0L) {
    return(list(
      ok = FALSE,
      status = "warn",
      summary = paste0("checksum mismatch against ", expected_label),
      details = paste0(
        "Changed files: ",
        paste(sort(digest_mismatches), collapse = ", ")
      )
    ))
  }

  expected_tree <- .or_default(expected_record$summary$tree_digest, "")
  current_tree <- .or_default(current_record$summary$tree_digest, "")

  if (!identical(expected_tree, current_tree)) {
    return(list(
      ok = FALSE,
      status = "warn",
      summary = paste0("tree digest mismatch against ", expected_label),
      details = paste0(
        "The overall tree digest for ",
        current_label,
        " does not match the recorded ",
        expected_label,
        " digest."
      )
    ))
  }

  list(
    ok = TRUE,
    status = "pass",
    summary = paste0("matches ", expected_label),
    details = character()
  )
}

# Write the current prune integrity record and return a summary.
.write_prune_integrity <- function(root) {
  record <- .current_prune_record(root)
  path <- .prune_integrity_record_path(root)
  .write_integrity_record(path, record)

  list(
    record = record,
    path = .strip_root_prefix(path, root)
  )
}

# Write the current generate integrity record and return a summary.
.write_generate_integrity <- function(root) {
  record <- .current_generate_record(root)
  path <- .generate_record_path(root)
  .write_integrity_record(path, record)

  list(
    record = record,
    path = .strip_root_prefix(path, root)
  )
}

# Compare the current prune-owned surface against the recorded prune output.
.check_prune_integrity <- function(root) {
  expected_path <- .prune_integrity_record_path(root)
  expected <- .read_integrity_record(expected_path)
  current <- .current_prune_record(root)
  comparison <- .compare_integrity_record(
    expected_record = expected,
    current_record = current,
    expected_label = "prune output",
    current_label = "current prune surface"
  )

  comparison$record_path <- .strip_root_prefix(expected_path, root)
  comparison$current_record <- current
  comparison
}

# Compare the current generate-owned surface against the recorded generate
# output.
.check_generate_integrity <- function(root) {
  expected_path <- .generate_record_path(root)
  expected <- .read_integrity_record(expected_path)
  current <- .current_generate_record(root)
  comparison <- .compare_integrity_record(
    expected_record = expected,
    current_record = current,
    expected_label = "generate output",
    current_label = "current generate surface"
  )

  comparison$record_path <- .strip_root_prefix(expected_path, root)
  comparison$current_record <- current
  comparison
}

# Return one CLI status label for an integrity comparison.
.integrity_cli_status <- function(status) {
  if (identical(status, "pass")) {
    "Pass"
  } else {
    "Warn"
  }
}
