# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-animated-image` component
#'
#' Generated wrapper for the Web Awesome `wa-animated-image` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param alt A description of the image used by assistive devices.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param play Plays the animation. When this attribute is remove, the
#' animation will pause.
#' @param src The path to the image to load.
#' @param pause_icon Optional pause icon to use instead of the default.
#' Works best with `<wa-icon>`.
#' @param play_icon Optional play icon to use instead of the default.
#' Works best with `<wa-icon>`.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_animated_image <- function(
  ...,
  id = NULL,
  alt = NULL,
  dir = NULL,
  lang = NULL,
  play = NULL,
  src = NULL,
  pause_icon = NULL,
  play_icon = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(pause_icon, "pause-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(play_icon, "play-icon")
    )
  )


  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "alt" = alt,
      "dir" = dir,
      "lang" = lang,
      "play" = play,
      "src" = src
    ),
    boolean_names = c("play"),
    boolean_arg_names = c("play" = "play")
  )

  do.call(
    .wa_component,
    c(
      list("wa-animated-image", .attrs = attrs),
      children
    )
  )
}
# nolint end
