# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-avatar` component
#'
#' Generated wrapper for the Web Awesome `wa-avatar` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param label A label to use to describe the avatar to assistive
#' devices. Defaults to `` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param image The image source to use for the avatar. Defaults to ``
#' when omitted.
#' @param initials Initials to use as a fallback when no image is
#' available (1-2 characters max recommended). Defaults to `` when
#' omitted.
#' @param lang Optional Web Awesome attribute.
#' @param loading Indicates how the browser should load the image. Must be
#' one of `"eager"`, `"lazy"`. Defaults to `eager` when omitted.
#' @param shape The shape of the avatar. Must be one of `"circle"`,
#' `"rounded"`, `"square"`. Defaults to `circle` when omitted.
#' @param icon The default icon to use when no image or initials are
#' present. Works best with `<wa-icon>`.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_avatar <- function(
  ...,
  id = NULL,
  label = NULL,
  dir = NULL,
  image = NULL,
  initials = NULL,
  lang = NULL,
  loading = NULL,
  shape = NULL,
  icon = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(icon, "icon")
    )
  )

  if (!is.null(loading)) {
    loading <- .wa_match_arg(
      loading,
      "loading",
      c(
        "eager",
        "lazy"
      )
    )
  }

  if (!is.null(shape)) {
    shape <- .wa_match_arg(
      shape,
      "shape",
      c(
        "circle",
        "rounded",
        "square"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "label" = label,
      "dir" = dir,
      "image" = image,
      "initials" = initials,
      "lang" = lang,
      "loading" = loading,
      "shape" = shape
    ),
    boolean_names = character(),
    boolean_arg_names = NULL
  )

  do.call(
    .wa_component,
    c(
      list("wa-avatar", .attrs = attrs),
      children
    )
  )
}
# nolint end
