# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-button-group` component
#'
#' Generated wrapper for the Web Awesome `wa-button-group` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param label A label to use for the button group. This won't be
#' displayed on the screen, but it will be announced by assistive devices
#' when interacting with the control and is strongly recommended. Defaults
#' to `` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param orientation The button group's orientation. Must be one of
#' `"horizontal"`, `"vertical"`. Defaults to `horizontal` when omitted.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_button_group <- function(
  ...,
  id = NULL,
  label = NULL,
  dir = NULL,
  lang = NULL,
  orientation = NULL
) {
  children <- list(...)
  if (!is.null(orientation)) {
    orientation <- .wa_match_arg(
      orientation,
      "orientation",
      c(
        "horizontal",
        "vertical"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "label" = label,
      "dir" = dir,
      "lang" = lang,
      "orientation" = orientation
    ),
    boolean_names = character(),
    boolean_arg_names = NULL
  )

  do.call(
    .wa_component,
    c(
      list("wa-button-group", .attrs = attrs),
      children
    )
  )
}
# nolint end
