# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-breadcrumb` component
#'
#' Generated wrapper for the Web Awesome `wa-breadcrumb` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param label String. Default: `""`. The label to use for the breadcrumb
#' control. This will not be shown on the screen, but it will be announced
#' by screen readers and other assistive devices to provide more context
#' for users.
#' @param dir String. Optional Web Awesome attribute.
#' @param lang String. Optional Web Awesome attribute.
#' @param separator The separator to use between breadcrumb items. Works
#' best with `<wa-icon>`.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_breadcrumb <- function(
  ...,
  id = NULL,
  class = NULL,
  style = NULL,
  label = NULL,
  dir = NULL,
  lang = NULL,
  separator = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(separator, "separator")
    )
  )



  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "class" = class,
      "style" = style,
      "label" = label,
      "dir" = dir,
      "lang" = lang
    ),
    boolean_names = character(),
    boolean_arg_names = NULL
  )

  do.call(
    .wa_component,
    c(
      list("wa-breadcrumb", .attrs = attrs),
      children
    )
  )
}
# nolint end
