# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-button` component
#'
#' Generated wrapper for the Web Awesome `wa-button` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param value The value of the button, submitted as a pair with the
#' button's name as part of the form data, but only when this button is
#' the submitter. This attribute is ignored when `href` is present.
#' @param disabled Disables the button.
#' @param name The name of the button, submitted as a name/value pair with
#' form data, but only when this button is the submitter. This attribute
#' is ignored when `href` is present.
#' @param appearance The button's visual appearance.
#' @param custom_error Optional Web Awesome attribute.
#' @param dir Optional Web Awesome attribute.
#' @param download Tells the browser to download the linked file as this
#' filename. Only used when `href` is present.
#' @param formaction Used to override the form owner's `action` attribute.
#' @param formenctype Used to override the form owner's `enctype`
#' attribute.
#' @param formmethod Used to override the form owner's `method` attribute.
#' @param formnovalidate Used to override the form owner's `novalidate`
#' attribute.
#' @param formtarget Used to override the form owner's `target` attribute.
#' @param href When set, the underlying button will be rendered as an
#' `<a>` with this `href` instead of a `<button>`.
#' @param lang Optional Web Awesome attribute.
#' @param loading Draws the button in a loading state.
#' @param pill Draws a pill-style button with rounded edges.
#' @param rel When using `href`, this attribute will map to the underlying
#' link's `rel` attribute.
#' @param size The button's size.
#' @param target Tells the browser where to open the link. Only used when
#' `href` is present.
#' @param title Optional Web Awesome attribute.
#' @param type The type of button. Note that the default value is `button`
#' instead of `submit`, which is opposite of how native `<button>`
#' elements behave. When the type is `submit`, the button will submit the
#' surrounding form.
#' @param variant The button's theme variant. Defaults to `neutral` if not
#' within another element with a variant.
#' @param with_caret Draws the button with a caret. Used to indicate that
#' the button triggers a dropdown menu or similar behavior.
#' @param end An element, such as `<wa-icon>`, placed after the label.
#' @param start An element, such as `<wa-icon>`, placed before the label.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_button <- function(
  ...,
  id = NULL,
  value = NULL,
  disabled = NULL,
  name = NULL,
  appearance = NULL,
  custom_error = NULL,
  dir = NULL,
  download = NULL,
  formaction = NULL,
  formenctype = NULL,
  formmethod = NULL,
  formnovalidate = NULL,
  formtarget = NULL,
  href = NULL,
  lang = NULL,
  loading = NULL,
  pill = NULL,
  rel = NULL,
  size = NULL,
  target = NULL,
  title = NULL,
  type = NULL,
  variant = NULL,
  with_caret = NULL,
  end = NULL,
  start = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(end, "end")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(start, "start")
    )
  )

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "value" = value,
      "disabled" = disabled,
      "name" = name,
      "appearance" = appearance,
      "custom-error" = custom_error,
      "dir" = dir,
      "download" = download,
      "formaction" = formaction,
      "formenctype" = formenctype,
      "formmethod" = formmethod,
      "formnovalidate" = formnovalidate,
      "formtarget" = formtarget,
      "href" = href,
      "lang" = lang,
      "loading" = loading,
      "pill" = pill,
      "rel" = rel,
      "size" = size,
      "target" = target,
      "title" = title,
      "type" = type,
      "variant" = variant,
      "with-caret" = with_caret
    ),
    boolean_names = c(
      "disabled",
      "formnovalidate",
      "loading",
      "pill",
      "with-caret"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-button", .attrs = attrs),
      children
    )
  )
}
# nolint end
