# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-carousel` component
#'
#' Generated wrapper for the Web Awesome `wa-carousel` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param autoplay When set, the slides will scroll automatically when the
#' user is not interacting with them.
#' @param autoplay_interval Specifies the amount of time, in milliseconds,
#' between each automatic scroll.
#' @param current_slide Optional Web Awesome attribute.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param loop When set, allows the user to navigate the carousel in the
#' same direction indefinitely.
#' @param mouse_dragging When set, it is possible to scroll through the
#' slides by dragging them with the mouse.
#' @param navigation When set, show the carousel's navigation.
#' @param orientation Specifies the orientation in which the carousel will
#' lay out.
#' @param pagination When set, show the carousel's pagination indicators.
#' @param slides Optional Web Awesome attribute.
#' @param slides_per_move Specifies the number of slides the carousel will
#' advance when scrolling, useful when specifying a `slides-per-page`
#' greater than one. It can't be higher than `slides-per-page`.
#' @param slides_per_page Specifies how many slides should be shown at a
#' given time.
#' @param next_icon Optional next icon to use instead of the default.
#' Works best with `<wa-icon>`.
#' @param previous_icon Optional previous icon to use instead of the
#' default. Works best with `<wa-icon>`.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_carousel <- function(
  ...,
  id = NULL,
  autoplay = NULL,
  autoplay_interval = NULL,
  current_slide = NULL,
  dir = NULL,
  lang = NULL,
  loop = NULL,
  mouse_dragging = NULL,
  navigation = NULL,
  orientation = NULL,
  pagination = NULL,
  slides = NULL,
  slides_per_move = NULL,
  slides_per_page = NULL,
  next_icon = NULL,
  previous_icon = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(next_icon, "next-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(previous_icon, "previous-icon")
    )
  )

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "autoplay" = autoplay,
      "autoplay-interval" = autoplay_interval,
      "currentSlide" = current_slide,
      "dir" = dir,
      "lang" = lang,
      "loop" = loop,
      "mouse-dragging" = mouse_dragging,
      "navigation" = navigation,
      "orientation" = orientation,
      "pagination" = pagination,
      "slides" = slides,
      "slides-per-move" = slides_per_move,
      "slides-per-page" = slides_per_page
    ),
    boolean_names = c(
      "autoplay",
      "loop",
      "mouse-dragging",
      "navigation",
      "pagination"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-carousel", .attrs = attrs),
      children
    )
  )
}
# nolint end
