# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-callout` component
#'
#' Generated wrapper for the Web Awesome `wa-callout` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param appearance The callout's visual appearance. Must be one of
#' `"accent"`, `"filled"`, `"filled-outlined"`, `"outlined"`, `"plain"`.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param size The callout's size. Must be one of `"large"`, `"medium"`,
#' `"small"`. Defaults to `medium` when omitted.
#' @param variant The callout's theme variant. Defaults to `brand` if not
#' within another element with a variant. Must be one of `"brand"`,
#' `"danger"`, `"neutral"`, `"success"`, `"warning"`. Defaults to `brand`
#' when omitted.
#' @param icon An icon to show in the callout. Works best with
#' `<wa-icon>`.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_callout <- function(
  ...,
  id = NULL,
  appearance = NULL,
  dir = NULL,
  lang = NULL,
  size = NULL,
  variant = NULL,
  icon = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(icon, "icon")
    )
  )

  if (!is.null(appearance)) {
    appearance <- .wa_match_arg(
      appearance,
      "appearance",
      c(
        "accent",
        "filled",
        "filled-outlined",
        "outlined",
        "plain"
      )
    )
  }

  if (!is.null(size)) {
    size <- .wa_match_arg(
      size,
      "size",
      c(
        "large",
        "medium",
        "small"
      )
    )
  }

  if (!is.null(variant)) {
    variant <- .wa_match_arg(
      variant,
      "variant",
      c(
        "brand",
        "danger",
        "neutral",
        "success",
        "warning"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "appearance" = appearance,
      "dir" = dir,
      "lang" = lang,
      "size" = size,
      "variant" = variant
    ),
    boolean_names = character(),
    boolean_arg_names = NULL
  )

  do.call(
    .wa_component,
    c(
      list("wa-callout", .attrs = attrs),
      children
    )
  )
}
# nolint end
