# Generated by tools/generate_components.R. Do not edit by hand.

#' Create a `wa-checkbox` component
#'
#' Generated wrapper for the Web Awesome `wa-checkbox` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute.
#' @param value The value of the checkbox, submitted as a name/value pair with form data.
#' @param checked The default value of the form control. Primarily used for resetting the form control.
#' @param disabled Disables the checkbox.
#' @param hint The checkbox's hint. If you need to display HTML, use the `hint` slot instead.
#' @param name The name of the checkbox, submitted as a name/value pair with form data.
#' @param custom_error Optional Web Awesome attribute.
#' @param dir Optional Web Awesome attribute.
#' @param indeterminate Draws the checkbox in an indeterminate state. This is usually applied to checkboxes that represents a "select all/none" behavior when associated checkboxes have a mix of checked and unchecked states.
#' @param lang Optional Web Awesome attribute.
#' @param required Makes the checkbox a required field.
#' @param size The checkbox's size.
#' @param title Optional Web Awesome attribute.
#' @param hint_slot Text that describes how to use the checkbox. Alternatively, you can use the `hint` attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_checkbox <- function(
  ...,
  id = NULL,
  value = NULL,
  checked = NULL,
  disabled = NULL,
  hint = NULL,
  name = NULL,
  custom_error = NULL,
  dir = NULL,
  indeterminate = NULL,
  lang = NULL,
  required = NULL,
  size = NULL,
  title = NULL,
  hint_slot = NULL
) {
  children <- list(...)
  children <- c(children, list(.wa_slot(hint_slot, "hint")))

  attrs <- .wa_normalize_attrs(
    list(
    "id" = id,
    "value" = value,
    "checked" = checked,
    "disabled" = disabled,
    "hint" = hint,
    "name" = name,
    "custom-error" = custom_error,
    "dir" = dir,
    "indeterminate" = indeterminate,
    "lang" = lang,
    "required" = required,
    "size" = size,
    "title" = title
  ),
    boolean_names = c("checked", "disabled", "indeterminate", "required")
  )

  do.call(
    .wa_component,
    c(
      list("wa-checkbox", .attrs = attrs),
      children
    )
  )
}
