# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-card` component
#'
#' Generated wrapper for the Web Awesome `wa-card` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param appearance The card's visual appearance. Must be one of
#' `"accent"`, `"filled"`, `"filled-outlined"`, `"outlined"`, `"plain"`.
#' Defaults to `outlined` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param orientation Renders the card's orientation * Must be one of
#' `"horizontal"`, `"vertical"`. Defaults to `vertical` when omitted.
#' @param actions An optional actions section to render at the end for the
#' horizontal card.
#' @param footer An optional footer for the card.
#' @param footer_actions An optional actions section to render in the
#' footer of the vertical card.
#' @param header An optional header for the card.
#' @param header_actions An optional actions section to render in the
#' header of the vertical card.
#' @param media An optional media section to render at the start of the
#' card.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_card <- function(
  ...,
  id = NULL,
  appearance = NULL,
  dir = NULL,
  lang = NULL,
  orientation = NULL,
  actions = NULL,
  footer = NULL,
  footer_actions = NULL,
  header = NULL,
  header_actions = NULL,
  media = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(actions, "actions")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(footer, "footer")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(footer_actions, "footer-actions")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(header, "header")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(header_actions, "header-actions")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(media, "media")
    )
  )
  if (!is.null(appearance)) {
    appearance <- .wa_match_arg(
      appearance,
      "appearance",
      c(
        "accent",
        "filled",
        "filled-outlined",
        "outlined",
        "plain"
      )
    )
  }

  if (!is.null(orientation)) {
    orientation <- .wa_match_arg(
      orientation,
      "orientation",
      c(
        "horizontal",
        "vertical"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "appearance" = appearance,
      "dir" = dir,
      "lang" = lang,
      "orientation" = orientation
    ),
    boolean_names = character()
  )

  do.call(
    .wa_component,
    c(
      list("wa-card", .attrs = attrs),
      children
    )
  )
}
# nolint end
