# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-drawer` component
#'
#' Generated wrapper for the Web Awesome `wa-drawer` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param label The drawer's label as displayed in the header. You should
#' always include a relevant label, as it is required for proper
#' accessibility. If you need to display HTML, use the `label` slot
#' instead. Defaults to `` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param light_dismiss When enabled, the drawer will be closed when the
#' user clicks outside of it. Defaults to `true` when omitted.
#' @param open Indicates whether or not the drawer is open. Toggle this
#' attribute to show and hide the drawer. Defaults to `false` when
#' omitted.
#' @param placement The direction from which the drawer will open. Must be
#' one of `"bottom"`, `"end"`, `"start"`, `"top"`. Defaults to `end` when
#' omitted.
#' @param without_header Disables the header. This will also remove the
#' default close button. Defaults to `false` when omitted.
#' @param footer The drawer's footer, usually one or more buttons
#' representing various options.
#' @param header_actions Optional actions to add to the header. Works best
#' with `<wa-button>`.
#' @param label_slot The drawer's label. Alternatively, you can use the
#' `label` attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_drawer <- function(
  input_id,
  ...,
  label = NULL,
  dir = NULL,
  lang = NULL,
  light_dismiss = NULL,
  open = NULL,
  placement = NULL,
  without_header = NULL,
  footer = NULL,
  header_actions = NULL,
  label_slot = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(footer, "footer")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(header_actions, "header-actions")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(label_slot, "label")
    )
  )

  if (!is.null(placement)) {
    placement <- .wa_match_arg(
      placement,
      "placement",
      c(
        "bottom",
        "end",
        "start",
        "top"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "label" = label,
      "dir" = dir,
      "lang" = lang,
      "light-dismiss" = light_dismiss,
      "open" = open,
      "placement" = placement,
      "without-header" = without_header
    ),
    boolean_names = c(
      "light-dismiss",
      "open",
      "without-header"
    ),
    boolean_arg_names = c(
      "light-dismiss" = "light_dismiss",
      "open" = "open",
      "without-header" = "without_header"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-drawer", .attrs = attrs),
      children
    )
  )
}
# nolint end
