# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-dropdown` component
#'
#' Generated wrapper for the Web Awesome `wa-dropdown` component. When
#' used as a Shiny input, action semantics are exposed through
#' `input$<input_id>` and the latest selected dropdown item value is
#' exposed through `input$<input_id>_value`. The action input increments
#' on every selection, including repeated selection of the same item. The
#' companion value input reflects the selected item's `value`, returns
#' `NULL` when the selected item has no `value`, and preserves an explicit
#' empty string `""` when that is the selected item's value.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param dir Optional Web Awesome attribute.
#' @param distance The distance of the dropdown menu from its trigger.
#' Defaults to `0` when omitted.
#' @param lang Optional Web Awesome attribute.
#' @param open Opens or closes the dropdown. Defaults to `false` when
#' omitted.
#' @param placement The placement of the dropdown menu in reference to the
#' trigger. The menu will shift to a more optimal location if the
#' preferred placement doesn't have enough room. Must be one of
#' `"bottom"`, `"bottom-end"`, `"bottom-start"`, `"left"`, `"left-end"`,
#' `"left-start"`, `"right"`, `"right-end"`, `"right-start"`, `"top"`,
#' `"top-end"`, `"top-start"`. Defaults to `bottom-start` when omitted.
#' @param size The dropdown's size. Must be one of `"large"`, `"medium"`,
#' `"small"`. Defaults to `medium` when omitted.
#' @param skidding The offset of the dropdown menu along its trigger.
#' Defaults to `0` when omitted.
#' @param trigger The element that triggers the dropdown, such as a
#' `<wa-button>` or `<button>`.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_dropdown <- function(
  input_id,
  ...,
  dir = NULL,
  distance = NULL,
  lang = NULL,
  open = NULL,
  placement = NULL,
  size = NULL,
  skidding = NULL,
  trigger = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(trigger, "trigger")
    )
  )

  if (!is.null(placement)) {
    placement <- .wa_match_arg(
      placement,
      "placement",
      c(
        "bottom",
        "bottom-end",
        "bottom-start",
        "left",
        "left-end",
        "left-start",
        "right",
        "right-end",
        "right-start",
        "top",
        "top-end",
        "top-start"
      )
    )
  }

  if (!is.null(size)) {
    size <- .wa_match_arg(
      size,
      "size",
      c(
        "large",
        "medium",
        "small"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "dir" = dir,
      "distance" = distance,
      "lang" = lang,
      "open" = open,
      "placement" = placement,
      "size" = size,
      "skidding" = skidding
    ),
    boolean_names = c("open"),
    boolean_arg_names = c("open" = "open")
  )

  do.call(
    .wa_component,
    c(
      list("wa-dropdown", .attrs = attrs),
      children
    )
  )
}
# nolint end
