# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-details` component
#'
#' Generated wrapper for the Web Awesome `wa-details` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param disabled Disables the details so it can't be toggled. Defaults
#' to `false` when omitted.
#' @param name Groups related details elements. When one opens, others
#' with the same name will close.
#' @param appearance The element's visual appearance. Must be one of
#' `"filled"`, `"filled-outlined"`, `"outlined"`, `"plain"`. Defaults to
#' `outlined` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param icon_placement The location of the expand/collapse icon. Must be
#' one of `"end"`, `"start"`. Defaults to `end` when omitted.
#' @param lang Optional Web Awesome attribute.
#' @param open Indicates whether or not the details is open. You can
#' toggle this attribute to show and hide the details, or you can use the
#' `show()` and `hide()` methods and this attribute will reflect the
#' details' open state. Defaults to `false` when omitted.
#' @param summary The summary to show in the header. If you need to
#' display HTML, use the `summary` slot instead.
#' @param collapse_icon Optional collapse icon to use instead of the
#' default. Works best with `<wa-icon>`.
#' @param expand_icon Optional expand icon to use instead of the default.
#' Works best with `<wa-icon>`.
#' @param summary_slot The details' summary. Alternatively, you can use
#' the `summary` attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_details <- function(
  input_id,
  ...,
  disabled = NULL,
  name = NULL,
  appearance = NULL,
  dir = NULL,
  icon_placement = NULL,
  lang = NULL,
  open = NULL,
  summary = NULL,
  collapse_icon = NULL,
  expand_icon = NULL,
  summary_slot = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(collapse_icon, "collapse-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(expand_icon, "expand-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(summary_slot, "summary")
    )
  )
  if (!is.null(appearance)) {
    appearance <- .wa_match_arg(
      appearance,
      "appearance",
      c(
        "filled",
        "filled-outlined",
        "outlined",
        "plain"
      )
    )
  }

  if (!is.null(icon_placement)) {
    icon_placement <- .wa_match_arg(
      icon_placement,
      "icon_placement",
      c(
        "end",
        "start"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "disabled" = disabled,
      "name" = name,
      "appearance" = appearance,
      "dir" = dir,
      "icon-placement" = icon_placement,
      "lang" = lang,
      "open" = open,
      "summary" = summary
    ),
    boolean_names = c("disabled", "open"),
    boolean_arg_names = c(
      "disabled" = "disabled",
      "open" = "open"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-details", .attrs = attrs),
      children
    )
  )
}
# nolint end
