# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-format-number` component
#'
#' Generated wrapper for the Web Awesome `wa-format-number` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param value The number to format. Defaults to `0` when omitted.
#' @param currency The ISO 4217 currency code to use when formatting.
#' Defaults to `USD` when omitted.
#' @param currency_display How to display the currency. Must be one of
#' `"code"`, `"name"`, `"narrowSymbol"`, `"symbol"`. Defaults to `symbol`
#' when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param maximum_fraction_digits The maximum number of fraction digits to
#' use. Possible values are 0-100.
#' @param maximum_significant_digits The maximum number of significant
#' digits to use,. Possible values are 1-21.
#' @param minimum_fraction_digits The minimum number of fraction digits to
#' use. Possible values are 0-100.
#' @param minimum_integer_digits The minimum number of integer digits to
#' use. Possible values are 1-21.
#' @param minimum_significant_digits The minimum number of significant
#' digits to use. Possible values are 1-21.
#' @param type The formatting style to use. Must be one of `"currency"`,
#' `"decimal"`, `"percent"`. Defaults to `decimal` when omitted.
#' @param without_grouping Turns off grouping separators. Defaults to
#' `false` when omitted.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_format_number <- function(
  ...,
  id = NULL,
  value = NULL,
  currency = NULL,
  currency_display = NULL,
  dir = NULL,
  lang = NULL,
  maximum_fraction_digits = NULL,
  maximum_significant_digits = NULL,
  minimum_fraction_digits = NULL,
  minimum_integer_digits = NULL,
  minimum_significant_digits = NULL,
  type = NULL,
  without_grouping = NULL
) {
  children <- list(...)
  if (!is.null(currency_display)) {
    currency_display <- .wa_match_arg(
      currency_display,
      "currency_display",
      c(
        "code",
        "name",
        "narrowSymbol",
        "symbol"
      )
    )
  }

  if (!is.null(type)) {
    type <- .wa_match_arg(
      type,
      "type",
      c(
        "currency",
        "decimal",
        "percent"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "value" = value,
      "currency" = currency,
      "currency-display" = currency_display,
      "dir" = dir,
      "lang" = lang,
      "maximum-fraction-digits" = maximum_fraction_digits,
      "maximum-significant-digits" = maximum_significant_digits,
      "minimum-fraction-digits" = minimum_fraction_digits,
      "minimum-integer-digits" = minimum_integer_digits,
      "minimum-significant-digits" = minimum_significant_digits,
      "type" = type,
      "without-grouping" = without_grouping
    ),
    boolean_names = c("without-grouping")
  )

  do.call(
    .wa_component,
    c(
      list("wa-format-number", .attrs = attrs),
      children
    )
  )
}
# nolint end
