# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-format-bytes` component
#'
#' Generated wrapper for the Web Awesome `wa-format-bytes` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param value The number to format in bytes. Defaults to `0` when
#' omitted.
#' @param dir Optional Web Awesome attribute.
#' @param display Determines how to display the result, e.g. "100 bytes",
#' "100 b", or "100b". Must be one of `"long"`, `"narrow"`, `"short"`.
#' Defaults to `short` when omitted.
#' @param lang Optional Web Awesome attribute.
#' @param unit The type of unit to display. Must be one of `"bit"`,
#' `"byte"`. Defaults to `byte` when omitted.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_format_bytes <- function(
  ...,
  id = NULL,
  value = NULL,
  dir = NULL,
  display = NULL,
  lang = NULL,
  unit = NULL
) {
  children <- list(...)
  if (!is.null(display)) {
    display <- .wa_match_arg(
      display,
      "display",
      c(
        "long",
        "narrow",
        "short"
      )
    )
  }

  if (!is.null(unit)) {
    unit <- .wa_match_arg(
      unit,
      "unit",
      c(
        "bit",
        "byte"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "value" = value,
      "dir" = dir,
      "display" = display,
      "lang" = lang,
      "unit" = unit
    ),
    boolean_names = character()
  )

  do.call(
    .wa_component,
    c(
      list("wa-format-bytes", .attrs = attrs),
      children
    )
  )
}
# nolint end
