# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-intersection-observer` component
#'
#' Generated wrapper for the Web Awesome `wa-intersection-observer`
#' component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param disabled Deactivates the intersection observer functionality.
#' Defaults to `false` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param intersect_class CSS class applied to elements during
#' intersection. Automatically removed when elements leave the viewport,
#' enabling pure CSS styling based on visibility state. Defaults to ``
#' when omitted.
#' @param lang Optional Web Awesome attribute.
#' @param once If enabled, observation ceases after initial intersection.
#' Defaults to `false` when omitted.
#' @param root Element ID to define the viewport boundaries for tracked
#' targets. Defaults to `null` when omitted.
#' @param root_margin Offset space around the root boundary. Accepts
#' values like CSS margin syntax. Defaults to `0px` when omitted.
#' @param threshold One or more space-separated values representing
#' visibility percentages that trigger the observer callback. Defaults to
#' `0` when omitted.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_intersection_observer <- function(
  ...,
  id = NULL,
  disabled = NULL,
  dir = NULL,
  intersect_class = NULL,
  lang = NULL,
  once = NULL,
  root = NULL,
  root_margin = NULL,
  threshold = NULL
) {
  children <- list(...)



  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "disabled" = disabled,
      "dir" = dir,
      "intersect-class" = intersect_class,
      "lang" = lang,
      "once" = once,
      "root" = root,
      "root-margin" = root_margin,
      "threshold" = threshold
    ),
    boolean_names = c("disabled", "once"),
    boolean_arg_names = c(
      "disabled" = "disabled",
      "once" = "once"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-intersection-observer", .attrs = attrs),
      children
    )
  )
}
# nolint end
