# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-icon` component
#'
#' Generated wrapper for the Web Awesome `wa-icon` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param label An alternate description to use for assistive devices. If
#' omitted, the icon will be considered presentational and ignored by
#' assistive devices. Defaults to `` when omitted.
#' @param name The name of the icon to draw. Available names depend on the
#' icon library being used.
#' @param animation Sets the animation for the icon
#' @param auto_width Sets the width of the icon to match the cropped SVG
#' viewBox. This operates like the Font `fa-width-auto` class. Defaults to
#' `false` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param family The family of icons to choose from. For Font Awesome
#' Free, valid options include `classic` and `brands`. For Font Awesome
#' Pro subscribers, valid options include, `classic`, `sharp`, `duotone`,
#' `sharp-duotone`, and `brands`. A valid kit code must be present to show
#' pro icons via CDN. You can set `<html data-fa-kit-code="...">` to
#' provide one.
#' @param flip Sets the flip direction of the icon along the 'x'
#' (horizontal), 'y' (vertical), or 'both' axes.
#' @param lang Optional Web Awesome attribute.
#' @param library The name of a registered custom icon library. Defaults
#' to `default` when omitted.
#' @param rotate Sets the rotation degree of the icon Defaults to `0` when
#' omitted.
#' @param src An external URL of an SVG file. Be sure you trust the
#' content you are including, as it will be executed as code and can
#' result in XSS attacks.
#' @param swap_opacity Swaps the opacity of duotone icons. Defaults to
#' `false` when omitted.
#' @param variant The name of the icon's variant. For Font Awesome, valid
#' options include `thin`, `light`, `regular`, and `solid` for the
#' `classic` and `sharp` families. Some variants require a Font Awesome
#' Pro subscription. Custom icon libraries may or may not use this
#' property.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_icon <- function(
  ...,
  id = NULL,
  class = NULL,
  style = NULL,
  label = NULL,
  name = NULL,
  animation = NULL,
  auto_width = NULL,
  dir = NULL,
  family = NULL,
  flip = NULL,
  lang = NULL,
  library = NULL,
  rotate = NULL,
  src = NULL,
  swap_opacity = NULL,
  variant = NULL
) {
  children <- list(...)


  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "class" = class,
      "style" = style,
      "label" = label,
      "name" = name,
      "animation" = animation,
      "auto-width" = auto_width,
      "dir" = dir,
      "family" = family,
      "flip" = flip,
      "lang" = lang,
      "library" = library,
      "rotate" = rotate,
      "src" = src,
      "swap-opacity" = swap_opacity,
      "variant" = variant
    ),
    boolean_names = c("auto-width", "swap-opacity"),
    boolean_arg_names = c(
      "auto-width" = "auto_width",
      "swap-opacity" = "swap_opacity"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-icon", .attrs = attrs),
      children
    )
  )
}
# nolint end
