# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-mutation-observer` component
#'
#' Generated wrapper for the Web Awesome `wa-mutation-observer` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param disabled Boolean. Default: `FALSE`. Disables the observer.
#' @param attr String. Watches for changes to attributes. To watch only
#' specific attributes, separate them by a space, e.g. `attr="class id
#' title"`. To watch all attributes, use `*`.
#' @param attr_old_value Boolean. Default: `FALSE`. Indicates whether or
#' not the attribute's previous value should be recorded when monitoring
#' changes.
#' @param char_data Boolean. Default: `FALSE`. Watches for changes to the
#' character data contained within the node.
#' @param char_data_old_value Boolean. Default: `FALSE`. Indicates whether
#' or not the previous value of the node's text should be recorded.
#' @param child_list Boolean. Default: `FALSE`. Watches for the addition
#' or removal of new child nodes.
#' @param dir String. Optional Web Awesome attribute.
#' @param lang String. Optional Web Awesome attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_mutation_observer <- function(
  ...,
  id = NULL,
  class = NULL,
  style = NULL,
  disabled = NULL,
  attr = NULL,
  attr_old_value = NULL,
  char_data = NULL,
  char_data_old_value = NULL,
  child_list = NULL,
  dir = NULL,
  lang = NULL
) {
  children <- list(...)



  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "class" = class,
      "style" = style,
      "disabled" = disabled,
      "attr" = attr,
      "attr-old-value" = attr_old_value,
      "char-data" = char_data,
      "char-data-old-value" = char_data_old_value,
      "child-list" = child_list,
      "dir" = dir,
      "lang" = lang
    ),
    boolean_names = c(
      "disabled",
      "attr-old-value",
      "char-data",
      "char-data-old-value",
      "child-list"
    ),
    boolean_arg_names = c(
      "disabled" = "disabled",
      "attr-old-value" = "attr_old_value",
      "char-data" = "char_data",
      "char-data-old-value" = "char_data_old_value",
      "child-list" = "child_list"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-mutation-observer", .attrs = attrs),
      children
    )
  )
}
# nolint end
