# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-number-input` component
#'
#' Generated wrapper for the Web Awesome `wa-number-input` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param value The default value of the form control. Primarily used for
#' resetting the form control.
#' @param disabled Disables the form control.
#' @param label The input's label. If you need to display HTML, use the
#' `label` slot instead.
#' @param hint The input's hint. If you need to display HTML, use the
#' `hint` slot instead.
#' @param name The name of the input, submitted as a name/value pair with
#' form data.
#' @param appearance The input's visual appearance.
#' @param autocomplete Specifies what permission the browser has to
#' provide assistance in filling out form field values. Refer to this page
#' on MDN for available values.
#' @param autofocus Indicates that the input should receive focus on page
#' load.
#' @param custom_error Optional Web Awesome attribute.
#' @param dir Optional Web Awesome attribute.
#' @param enterkeyhint Used to customize the label or icon of the Enter
#' key on virtual keyboards.
#' @param inputmode Tells the browser what type of data will be entered by
#' the user, allowing it to display the appropriate virtual keyboard on
#' supportive devices.
#' @param lang Optional Web Awesome attribute.
#' @param max The input's maximum value.
#' @param min The input's minimum value.
#' @param pill Draws a pill-style input with rounded edges.
#' @param placeholder Placeholder text to show as a hint when the input is
#' empty.
#' @param readonly Makes the input readonly.
#' @param required Makes the input a required field.
#' @param size The input's size.
#' @param step Specifies the granularity that the value must adhere to, or
#' the special value `any` which means no stepping is implied, allowing
#' any numeric value.
#' @param title Optional Web Awesome attribute.
#' @param with_hint Used for SSR. Will determine if the SSRed component
#' will have the hint slot rendered on initial paint.
#' @param with_label Used for SSR. Will determine if the SSRed component
#' will have the label slot rendered on initial paint.
#' @param without_steppers Hides the increment/decrement stepper buttons.
#' @param decrement_icon An icon to use in lieu of the default decrement
#' icon.
#' @param end An element, such as `<wa-icon>`, placed at the end of the
#' input control (before steppers).
#' @param hint_slot Text that describes how to use the input.
#' Alternatively, you can use the `hint` attribute.
#' @param increment_icon An icon to use in lieu of the default increment
#' icon.
#' @param label_slot The input's label. Alternatively, you can use the
#' `label` attribute.
#' @param start An element, such as `<wa-icon>`, placed at the start of
#' the input control.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_number_input <- function(
  input_id,
  ...,
  value = NULL,
  disabled = NULL,
  label = NULL,
  hint = NULL,
  name = NULL,
  appearance = NULL,
  autocomplete = NULL,
  autofocus = NULL,
  custom_error = NULL,
  dir = NULL,
  enterkeyhint = NULL,
  inputmode = NULL,
  lang = NULL,
  max = NULL,
  min = NULL,
  pill = NULL,
  placeholder = NULL,
  readonly = NULL,
  required = NULL,
  size = NULL,
  step = NULL,
  title = NULL,
  with_hint = NULL,
  with_label = NULL,
  without_steppers = NULL,
  decrement_icon = NULL,
  end = NULL,
  hint_slot = NULL,
  increment_icon = NULL,
  label_slot = NULL,
  start = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(decrement_icon, "decrement-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(end, "end")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(hint_slot, "hint")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(increment_icon, "increment-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(label_slot, "label")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(start, "start")
    )
  )

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "value" = value,
      "disabled" = disabled,
      "label" = label,
      "hint" = hint,
      "name" = name,
      "appearance" = appearance,
      "autocomplete" = autocomplete,
      "autofocus" = autofocus,
      "custom-error" = custom_error,
      "dir" = dir,
      "enterkeyhint" = enterkeyhint,
      "inputmode" = inputmode,
      "lang" = lang,
      "max" = max,
      "min" = min,
      "pill" = pill,
      "placeholder" = placeholder,
      "readonly" = readonly,
      "required" = required,
      "size" = size,
      "step" = step,
      "title" = title,
      "with-hint" = with_hint,
      "with-label" = with_label,
      "without-steppers" = without_steppers
    ),
    boolean_names = c(
      "disabled",
      "autofocus",
      "pill",
      "readonly",
      "required",
      "with-hint",
      "with-label",
      "without-steppers"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-number-input", .attrs = attrs),
      children
    )
  )
}
# nolint end

# Generated by tools/generate_components.R. Do not edit by hand.

#' Update a `wa-number-input` component
#'
#' Generated update helper for the Web Awesome `wa-number-input` component.
#'
#' @param session Shiny session object.
#' @param input_id Input id of the component to update.
#' @param value Optional value to send to the component.
#' @param label Optional label text to send to the component.
#' @param hint Optional hint text to send to the component.
#' @param disabled Optional logical disabled state to send to the component.
#'
#' @return Invisibly returns `NULL`.
#'
#' @rdname wa_number_input
#' @export
update_wa_number_input <- function(
  session,
  input_id,
  value = NULL,
  label = NULL,
  hint = NULL,
  disabled = NULL
) {
  message <- Filter(
    Negate(is.null),
    list(
      value = value,
      label = label,
      hint = hint,
      disabled = disabled
    )
  )

  session$sendInputMessage(input_id, message)
  invisible(NULL)
}
