# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-option` component
#'
#' Generated wrapper for the Web Awesome `wa-option` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param value The option's value. When selected, the containing form
#' control will receive this value. The value must be unique from other
#' options in the same group. Values may not contain spaces, as spaces are
#' used as delimiters when listing multiple values. Defaults to `` when
#' omitted.
#' @param disabled Draws the option in a disabled state, preventing
#' selection. Defaults to `false` when omitted.
#' @param label The option’s plain text label. Usually automatically
#' generated, but can be useful to provide manually for cases involving
#' complex content.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param selected Selects an option initially. Defaults to `false` when
#' omitted.
#' @param end An element, such as `<wa-icon>`, placed after the label.
#' @param start An element, such as `<wa-icon>`, placed before the label.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_option <- function(
  ...,
  id = NULL,
  value = NULL,
  disabled = NULL,
  label = NULL,
  dir = NULL,
  lang = NULL,
  selected = NULL,
  end = NULL,
  start = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(end, "end")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(start, "start")
    )
  )


  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "value" = value,
      "disabled" = disabled,
      "label" = label,
      "dir" = dir,
      "lang" = lang,
      "selected" = selected
    ),
    boolean_names = c("disabled", "selected")
  )

  do.call(
    .wa_component,
    c(
      list("wa-option", .attrs = attrs),
      children
    )
  )
}
# nolint end
