# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-popover` component
#'
#' Generated wrapper for the Web Awesome `wa-popover` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param dir Optional Web Awesome attribute.
#' @param distance The distance in pixels from which to offset the popover
#' away from its target.
#' @param for The ID of the popover's anchor element. This must be an
#' interactive/focusable element such as a button.
#' @param lang Optional Web Awesome attribute.
#' @param open Shows or hides the popover.
#' @param placement The preferred placement of the popover. Note that the
#' actual placement may vary as needed to keep the popover inside of the
#' viewport.
#' @param skidding The distance in pixels from which to offset the popover
#' along its target.
#' @param without_arrow Removes the arrow from the popover.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_popover <- function(
  ...,
  id = NULL,
  dir = NULL,
  distance = NULL,
  `for` = NULL,
  lang = NULL,
  open = NULL,
  placement = NULL,
  skidding = NULL,
  without_arrow = NULL
) {
  children <- list(...)

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "dir" = dir,
      "distance" = distance,
      "for" = `for`,
      "lang" = lang,
      "open" = open,
      "placement" = placement,
      "skidding" = skidding,
      "without-arrow" = without_arrow
    ),
    boolean_names = c("open", "without-arrow")
  )

  do.call(
    .wa_component,
    c(
      list("wa-popover", .attrs = attrs),
      children
    )
  )
}
# nolint end
