# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-progress-bar` component
#'
#' Generated wrapper for the Web Awesome `wa-progress-bar` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param value Number. Default: `0`. The current progress as a
#' percentage, 0 to 100.
#' @param label String. Default: `""`. A custom label for assistive
#' devices.
#' @param dir String. Optional Web Awesome attribute.
#' @param indeterminate Boolean. Default: `FALSE`. When TRUE, percentage
#' is ignored, the label is hidden, and the progress bar is drawn in an
#' indeterminate state.
#' @param lang String. Optional Web Awesome attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_progress_bar <- function(
  ...,
  id = NULL,
  class = NULL,
  style = NULL,
  value = NULL,
  label = NULL,
  dir = NULL,
  indeterminate = NULL,
  lang = NULL
) {
  children <- list(...)

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "class" = class,
      "style" = style,
      "value" = value,
      "label" = label,
      "dir" = dir,
      "indeterminate" = indeterminate,
      "lang" = lang
    ),
    boolean_names = c("indeterminate"),
    boolean_arg_names = c("indeterminate" = "indeterminate")
  )

  do.call(
    .wa_component,
    c(
      list("wa-progress-bar", .attrs = attrs),
      children
    )
  )
}
# nolint end
