# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-progress-ring` component
#'
#' Generated wrapper for the Web Awesome `wa-progress-ring` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param value The current progress as a percentage, 0 to 100. Defaults
#' to `0` when omitted.
#' @param label A custom label for assistive devices. Defaults to `` when
#' omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_progress_ring <- function(
  ...,
  id = NULL,
  value = NULL,
  label = NULL,
  dir = NULL,
  lang = NULL
) {
  children <- list(...)



  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "value" = value,
      "label" = label,
      "dir" = dir,
      "lang" = lang
    ),
    boolean_names = character(),
    boolean_arg_names = NULL
  )

  do.call(
    .wa_component,
    c(
      list("wa-progress-ring", .attrs = attrs),
      children
    )
  )
}
# nolint end
