# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-qr-code` component
#'
#' Generated wrapper for the Web Awesome `wa-qr-code` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param value String. Default: `""`. The QR code's value.
#' @param label String. Default: `""`. The label for assistive devices to
#' announce. If unspecified, the value will be used instead.
#' @param background String. Default: `""`. The background color. This can
#' be any valid CSS color or `transparent`. It cannot be a CSS custom
#' property.
#' @param dir String. Optional Web Awesome attribute.
#' @param error_correction Enumerated string. Allowed values: `H`, `L`,
#' `M`, `Q`. Default: `H`. The level of error correction to use. Learn
#' more
#' @param fill String. Default: `""`. The fill color. This can be any
#' valid CSS color, but not a CSS custom property.
#' @param lang String. Optional Web Awesome attribute.
#' @param radius Number. Default: `0`. The edge radius of each module.
#' Must be between 0 and 0.5.
#' @param size Number. Default: `128`. The size of the QR code, in pixels.
#'
#' @section Shiny Bindings:
#' None.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_qr_code <- function(
  ...,
  id = NULL,
  class = NULL,
  style = NULL,
  value = NULL,
  label = NULL,
  background = NULL,
  dir = NULL,
  error_correction = NULL,
  fill = NULL,
  lang = NULL,
  radius = NULL,
  size = NULL
) {
  children <- list(...)

  if (!is.null(error_correction)) {
    error_correction <- .wa_match_arg(
      error_correction,
      "error_correction",
      c(
        "H",
        "L",
        "M",
        "Q"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "class" = class,
      "style" = style,
      "value" = value,
      "label" = label,
      "background" = background,
      "dir" = dir,
      "error-correction" = error_correction,
      "fill" = fill,
      "lang" = lang,
      "radius" = radius,
      "size" = size
    ),
    boolean_names = character(),
    boolean_arg_names = NULL
  )

  do.call(
    .wa_component,
    c(
      list("wa-qr-code", .attrs = attrs),
      children
    )
  )
}
# nolint end
