# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-qr-code` component
#'
#' Generated wrapper for the Web Awesome `wa-qr-code` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param value The QR code's value. Defaults to `` when omitted.
#' @param label The label for assistive devices to announce. If
#' unspecified, the value will be used instead. Defaults to `` when
#' omitted.
#' @param background The background color. This can be any valid CSS color
#' or `transparent`. It cannot be a CSS custom property. Defaults to ``
#' when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param error_correction The level of error correction to use. Learn
#' more Must be one of `"H"`, `"L"`, `"M"`, `"Q"`. Defaults to `H` when
#' omitted.
#' @param fill The fill color. This can be any valid CSS color, but not a
#' CSS custom property. Defaults to `` when omitted.
#' @param lang Optional Web Awesome attribute.
#' @param radius The edge radius of each module. Must be between 0 and
#' 0.5. Defaults to `0` when omitted.
#' @param size The size of the QR code, in pixels. Defaults to `128` when
#' omitted.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_qr_code <- function(
  ...,
  id = NULL,
  value = NULL,
  label = NULL,
  background = NULL,
  dir = NULL,
  error_correction = NULL,
  fill = NULL,
  lang = NULL,
  radius = NULL,
  size = NULL
) {
  children <- list(...)
  if (!is.null(error_correction)) {
    error_correction <- .wa_match_arg(
      error_correction,
      "error_correction",
      c(
        "H",
        "L",
        "M",
        "Q"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "value" = value,
      "label" = label,
      "background" = background,
      "dir" = dir,
      "error-correction" = error_correction,
      "fill" = fill,
      "lang" = lang,
      "radius" = radius,
      "size" = size
    ),
    boolean_names = character()
  )

  do.call(
    .wa_component,
    c(
      list("wa-qr-code", .attrs = attrs),
      children
    )
  )
}
# nolint end
