# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-rating` component
#'
#' Generated wrapper for the Web Awesome `wa-rating` component. When used
#' as a Shiny input, `input$<input_id>` reflects the component's current
#' value.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param value The current rating. Defaults to `0` when omitted.
#' @param disabled Disables the rating. Defaults to `false` when omitted.
#' @param label A label that describes the rating to assistive devices.
#' Defaults to `` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param get_symbol A function that customizes the symbol to be rendered.
#' The first and only argument is the rating's current value. The function
#' should return a string containing trusted HTML of the symbol to render
#' at the specified value. Works well with `<wa-icon>` elements.
#' @param lang Optional Web Awesome attribute.
#' @param max The highest rating to show. Defaults to `5` when omitted.
#' @param precision The precision at which the rating will increase and
#' decrease. For example, to allow half-star ratings, set this attribute
#' to `0.5`. Defaults to `1` when omitted.
#' @param readonly Makes the rating readonly. Defaults to `false` when
#' omitted.
#' @param size The component's size. Must be one of `"large"`, `"medium"`,
#' `"small"`. Defaults to `medium` when omitted.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_rating <- function(
  input_id,
  ...,
  class = NULL,
  style = NULL,
  value = NULL,
  disabled = NULL,
  label = NULL,
  dir = NULL,
  get_symbol = NULL,
  lang = NULL,
  max = NULL,
  precision = NULL,
  readonly = NULL,
  size = NULL
) {
  children <- list(...)

  if (!is.null(size)) {
    size <- .wa_match_arg(
      size,
      "size",
      c(
        "large",
        "medium",
        "small"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "class" = class,
      "style" = style,
      "value" = value,
      "disabled" = disabled,
      "label" = label,
      "dir" = dir,
      "getSymbol" = get_symbol,
      "lang" = lang,
      "max" = max,
      "precision" = precision,
      "readonly" = readonly,
      "size" = size
    ),
    boolean_names = c("disabled", "readonly"),
    boolean_arg_names = c(
      "disabled" = "disabled",
      "readonly" = "readonly"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-rating", .attrs = attrs),
      children
    )
  )
}
# nolint end
