# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-resize-observer` component
#'
#' Generated wrapper for the Web Awesome `wa-resize-observer` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param disabled Disables the observer. Defaults to `false` when
#' omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_resize_observer <- function(
  ...,
  id = NULL,
  disabled = NULL,
  dir = NULL,
  lang = NULL
) {
  children <- list(...)


  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "disabled" = disabled,
      "dir" = dir,
      "lang" = lang
    ),
    boolean_names = c("disabled"),
    boolean_arg_names = c("disabled" = "disabled")
  )

  do.call(
    .wa_component,
    c(
      list("wa-resize-observer", .attrs = attrs),
      children
    )
  )
}
# nolint end
