# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-radio` component
#'
#' Generated wrapper for the Web Awesome `wa-radio` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param value The radio's value. When selected, the radio group will
#' receive this value.
#' @param disabled Disables the radio. Defaults to `false` when omitted.
#' @param name The name of the input, submitted as a name/value pair with
#' form data. Defaults to `null` when omitted.
#' @param appearance The radio's visual appearance. Must be one of
#' `"button"`, `"default"`. Defaults to `default` when omitted.
#' @param custom_error Optional Web Awesome attribute. Defaults to `null`
#' when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param size The radio's size. When used inside a radio group, the size
#' will be determined by the radio group's size, which will override this
#' attribute. Must be one of `"large"`, `"medium"`, `"small"`.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_radio <- function(
  ...,
  id = NULL,
  class = NULL,
  style = NULL,
  value = NULL,
  disabled = NULL,
  name = NULL,
  appearance = NULL,
  custom_error = NULL,
  dir = NULL,
  lang = NULL,
  size = NULL
) {
  children <- list(...)

  if (!is.null(appearance)) {
    appearance <- .wa_match_arg(
      appearance,
      "appearance",
      c(
        "button",
        "default"
      )
    )
  }

  if (!is.null(size)) {
    size <- .wa_match_arg(
      size,
      "size",
      c(
        "large",
        "medium",
        "small"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "class" = class,
      "style" = style,
      "value" = value,
      "disabled" = disabled,
      "name" = name,
      "appearance" = appearance,
      "custom-error" = custom_error,
      "dir" = dir,
      "lang" = lang,
      "size" = size
    ),
    boolean_names = c("disabled"),
    boolean_arg_names = c("disabled" = "disabled")
  )

  do.call(
    .wa_component,
    c(
      list("wa-radio", .attrs = attrs),
      children
    )
  )
}
# nolint end
