# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-rating` component
#'
#' Generated wrapper for the Web Awesome `wa-rating` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param value The current rating.
#' @param disabled Disables the rating.
#' @param label A label that describes the rating to assistive devices.
#' @param dir Optional Web Awesome attribute.
#' @param get_symbol A function that customizes the symbol to be rendered.
#' The first and only argument is the rating's current value. The function
#' should return a string containing trusted HTML of the symbol to render
#' at the specified value. Works well with `<wa-icon>` elements.
#' @param lang Optional Web Awesome attribute.
#' @param max The highest rating to show.
#' @param precision The precision at which the rating will increase and
#' decrease. For example, to allow half-star ratings, set this attribute
#' to `0.5`.
#' @param readonly Makes the rating readonly.
#' @param size The component's size.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_rating <- function(
  input_id,
  ...,
  value = NULL,
  disabled = NULL,
  label = NULL,
  dir = NULL,
  get_symbol = NULL,
  lang = NULL,
  max = NULL,
  precision = NULL,
  readonly = NULL,
  size = NULL
) {
  children <- list(...)

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "value" = value,
      "disabled" = disabled,
      "label" = label,
      "dir" = dir,
      "getSymbol" = get_symbol,
      "lang" = lang,
      "max" = max,
      "precision" = precision,
      "readonly" = readonly,
      "size" = size
    ),
    boolean_names = c("disabled", "readonly")
  )

  do.call(
    .wa_component,
    c(
      list("wa-rating", .attrs = attrs),
      children
    )
  )
}
# nolint end
