# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-radio-group` component
#'
#' Generated wrapper for the Web Awesome `wa-radio-group` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param value The default value of the form control. Primarily used for
#' resetting the form control. This wrapper argument sets the HTML `value`
#' attribute, which maps to the component's `defaultValue` field/property
#' rather than its live `value` property.
#' @param disabled Disables the radio group and all child radios. Defaults
#' to `false` when omitted.
#' @param label The radio group's label. Required for proper
#' accessibility. If you need to display HTML, use the `label` slot
#' instead. Defaults to `` when omitted.
#' @param hint The radio groups's hint. If you need to display HTML, use
#' the `hint` slot instead. Defaults to `` when omitted.
#' @param name The name of the radio group, submitted as a name/value pair
#' with form data. Defaults to `null` when omitted.
#' @param custom_error Optional Web Awesome attribute. Defaults to `null`
#' when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param orientation The orientation in which to show radio items. Must
#' be one of `"horizontal"`, `"vertical"`. Defaults to `vertical` when
#' omitted.
#' @param required Ensures a child radio is checked before allowing the
#' containing form to submit. Defaults to `false` when omitted.
#' @param size The radio group's size. When present, this size will be
#' applied to all `<wa-radio>` items inside. Must be one of `"large"`,
#' `"medium"`, `"small"`.
#' @param with_hint Used for SSR. if true, will show slotted hint on
#' initial render. Defaults to `false` when omitted.
#' @param with_label Used for SSR. if true, will show slotted label on
#' initial render. Defaults to `false` when omitted.
#' @param hint_slot Text that describes how to use the radio group.
#' Alternatively, you can use the `hint` attribute.
#' @param label_slot The radio group's label. Required for proper
#' accessibility. Alternatively, you can use the `label` attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_radio_group <- function(
  input_id,
  ...,
  class = NULL,
  style = NULL,
  value = NULL,
  disabled = NULL,
  label = NULL,
  hint = NULL,
  name = NULL,
  custom_error = NULL,
  dir = NULL,
  lang = NULL,
  orientation = NULL,
  required = NULL,
  size = NULL,
  with_hint = NULL,
  with_label = NULL,
  hint_slot = NULL,
  label_slot = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(hint_slot, "hint")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(label_slot, "label")
    )
  )

  if (!is.null(orientation)) {
    orientation <- .wa_match_arg(
      orientation,
      "orientation",
      c(
        "horizontal",
        "vertical"
      )
    )
  }

  if (!is.null(size)) {
    size <- .wa_match_arg(
      size,
      "size",
      c(
        "large",
        "medium",
        "small"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "class" = class,
      "style" = style,
      "value" = value,
      "disabled" = disabled,
      "label" = label,
      "hint" = hint,
      "name" = name,
      "custom-error" = custom_error,
      "dir" = dir,
      "lang" = lang,
      "orientation" = orientation,
      "required" = required,
      "size" = size,
      "with-hint" = with_hint,
      "with-label" = with_label
    ),
    boolean_names = c(
      "disabled",
      "required",
      "with-hint",
      "with-label"
    ),
    boolean_arg_names = c(
      "disabled" = "disabled",
      "required" = "required",
      "with-hint" = "with_hint",
      "with-label" = "with_label"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-radio-group", .attrs = attrs),
      children
    )
  )
}
# nolint end
