# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-spinner` component
#'
#' Generated wrapper for the Web Awesome `wa-spinner` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_spinner <- function(
  ...,
  id = NULL,
  class = NULL,
  style = NULL,
  dir = NULL,
  lang = NULL
) {
  children <- list(...)



  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "class" = class,
      "style" = style,
      "dir" = dir,
      "lang" = lang
    ),
    boolean_names = character(),
    boolean_arg_names = NULL
  )

  do.call(
    .wa_component,
    c(
      list("wa-spinner", .attrs = attrs),
      children
    )
  )
}
# nolint end
