# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-select` component
#'
#' Generated wrapper for the Web Awesome `wa-select` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param value The select's value. This will be a string for single
#' select or an array for multi-select.
#' @param disabled Disables the select control.
#' @param label The select's label. If you need to display HTML, use the
#' `label` slot instead.
#' @param hint The select's hint. If you need to display HTML, use the
#' `hint` slot instead.
#' @param name The name of the select, submitted as a name/value pair with
#' form data.
#' @param appearance The select's visual appearance.
#' @param custom_error Optional Web Awesome attribute.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param max_options_visible The maximum number of selected options to
#' show when `multiple` is true. After the maximum, "+n" will be shown to
#' indicate the number of additional items that are selected. Set to 0 to
#' remove the limit.
#' @param multiple Allows more than one option to be selected.
#' @param open Indicates whether or not the select is open. You can toggle
#' this attribute to show and hide the menu, or you can use the `show()`
#' and `hide()` methods and this attribute will reflect the select's open
#' state.
#' @param pill Draws a pill-style select with rounded edges.
#' @param placeholder Placeholder text to show as a hint when the select
#' is empty.
#' @param placement The preferred placement of the select's menu. Note
#' that the actual placement may vary as needed to keep the listbox inside
#' of the viewport.
#' @param required The select's required attribute.
#' @param size The select's size.
#' @param with_clear Adds a clear button when the select is not empty.
#' @param clear_icon An icon to use in lieu of the default clear icon.
#' @param end An element, such as `<wa-icon>`, placed at the end of the
#' combobox.
#' @param expand_icon The icon to show when the control is expanded and
#' collapsed. Rotates on open and close.
#' @param hint_slot Text that describes how to use the input.
#' Alternatively, you can use the `hint` attribute.
#' @param label_slot The input's label. Alternatively, you can use the
#' `label` attribute.
#' @param start An element, such as `<wa-icon>`, placed at the start of
#' the combobox.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_select <- function(
  input_id,
  ...,
  value = NULL,
  disabled = NULL,
  label = NULL,
  hint = NULL,
  name = NULL,
  appearance = NULL,
  custom_error = NULL,
  dir = NULL,
  lang = NULL,
  max_options_visible = NULL,
  multiple = NULL,
  open = NULL,
  pill = NULL,
  placeholder = NULL,
  placement = NULL,
  required = NULL,
  size = NULL,
  with_clear = NULL,
  clear_icon = NULL,
  end = NULL,
  expand_icon = NULL,
  hint_slot = NULL,
  label_slot = NULL,
  start = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(clear_icon, "clear-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(end, "end")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(expand_icon, "expand-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(hint_slot, "hint")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(label_slot, "label")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(start, "start")
    )
  )

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "value" = value,
      "disabled" = disabled,
      "label" = label,
      "hint" = hint,
      "name" = name,
      "appearance" = appearance,
      "custom-error" = custom_error,
      "dir" = dir,
      "lang" = lang,
      "max-options-visible" = max_options_visible,
      "multiple" = multiple,
      "open" = open,
      "pill" = pill,
      "placeholder" = placeholder,
      "placement" = placement,
      "required" = required,
      "size" = size,
      "with-clear" = with_clear
    ),
    boolean_names = c(
      "disabled",
      "multiple",
      "open",
      "pill",
      "required",
      "with-clear"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-select", .attrs = attrs),
      children
    )
  )
}
# nolint end

# Generated by tools/generate_components.R. Do not edit by hand.

#' Update a `wa-select` component
#'
#' Generated update helper for the Web Awesome `wa-select` component.
#'
#' @param session Shiny session object.
#' @param input_id Input id of the component to update.
#' @param value Optional value to send to the component.
#' @param label Optional label text to send to the component.
#' @param hint Optional hint text to send to the component.
#' @param disabled Optional logical disabled state to send to the component.
#'
#' @return Invisibly returns `NULL`.
#'
#' @rdname wa_select
#' @export
update_wa_select <- function(
  session,
  input_id,
  value = NULL,
  label = NULL,
  hint = NULL,
  disabled = NULL
) {
  message <- Filter(
    Negate(is.null),
    list(
      value = value,
      label = label,
      hint = hint,
      disabled = disabled
    )
  )

  session$sendInputMessage(input_id, message)
  invisible(NULL)
}
