# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-slider` component
#'
#' <wa-slider>
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param value The default value of the form control. Primarily used for
#' resetting the form control. This wrapper argument sets the HTML `value`
#' attribute, which maps to the component's `defaultValue` field/property
#' rather than its live `value` property.
#' @param disabled Disables the slider. Defaults to `false` when omitted.
#' @param label The slider's label. If you need to provide HTML in the
#' label, use the `label` slot instead. Defaults to `` when omitted.
#' @param hint The slider hint. If you need to display HTML, use the hint
#' slot instead. Defaults to `` when omitted.
#' @param name The name of the slider. This will be submitted with the
#' form as a name/value pair. Defaults to `null` when omitted.
#' @param autofocus Tells the browser to focus the slider when the page
#' loads or a dialog is shown.
#' @param custom_error Optional Web Awesome attribute. Defaults to `null`
#' when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param indicator_offset The starting value from which to draw the
#' slider's fill, which is based on its current value.
#' @param lang Optional Web Awesome attribute.
#' @param max The maximum value allowed. Defaults to `100` when omitted.
#' @param max_value The maximum value of a range selection. Used only when
#' range attribute is set. Defaults to `50` when omitted.
#' @param min The minimum value allowed. Defaults to `0` when omitted.
#' @param min_value The minimum value of a range selection. Used only when
#' range attribute is set. Defaults to `0` when omitted.
#' @param orientation The orientation of the slider. Must be one of
#' `"horizontal"`, `"vertical"`. Defaults to `horizontal` when omitted.
#' @param range Converts the slider to a range slider with two thumbs.
#' Defaults to `false` when omitted.
#' @param readonly Makes the slider a read-only field. Defaults to `false`
#' when omitted.
#' @param required Makes the slider a required field. Defaults to `false`
#' when omitted.
#' @param size The slider's size. Must be one of `"large"`, `"medium"`,
#' `"small"`. Defaults to `medium` when omitted.
#' @param step The granularity the value must adhere to when incrementing
#' and decrementing. Defaults to `1` when omitted.
#' @param tooltip_distance The distance of the tooltip from the slider's
#' thumb. Defaults to `8` when omitted.
#' @param tooltip_placement The placement of the tooltip in reference to
#' the slider's thumb. Must be one of `"bottom"`, `"left"`, `"right"`,
#' `"top"`. Defaults to `top` when omitted.
#' @param with_markers Draws markers at each step along the slider.
#' Defaults to `false` when omitted.
#' @param with_tooltip Draws a tooltip above the thumb when the control
#' has focus or is dragged. Defaults to `false` when omitted.
#' @param hint_slot Text that describes how to use the input.
#' Alternatively, you can use the `hint` attribute. instead.
#' @param label_slot The slider label. Alternatively, you can use the
#' `label` attribute.
#' @param reference One or more reference labels to show visually below
#' the slider.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_slider <- function(
  input_id,
  ...,
  value = NULL,
  disabled = NULL,
  label = NULL,
  hint = NULL,
  name = NULL,
  autofocus = NULL,
  custom_error = NULL,
  dir = NULL,
  indicator_offset = NULL,
  lang = NULL,
  max = NULL,
  max_value = NULL,
  min = NULL,
  min_value = NULL,
  orientation = NULL,
  range = NULL,
  readonly = NULL,
  required = NULL,
  size = NULL,
  step = NULL,
  tooltip_distance = NULL,
  tooltip_placement = NULL,
  with_markers = NULL,
  with_tooltip = NULL,
  hint_slot = NULL,
  label_slot = NULL,
  reference = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(hint_slot, "hint")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(label_slot, "label")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(reference, "reference")
    )
  )

  if (!is.null(orientation)) {
    orientation <- .wa_match_arg(
      orientation,
      "orientation",
      c(
        "horizontal",
        "vertical"
      )
    )
  }

  if (!is.null(size)) {
    size <- .wa_match_arg(
      size,
      "size",
      c(
        "large",
        "medium",
        "small"
      )
    )
  }

  if (!is.null(tooltip_placement)) {
    tooltip_placement <- .wa_match_arg(
      tooltip_placement,
      "tooltip_placement",
      c(
        "bottom",
        "left",
        "right",
        "top"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "value" = value,
      "disabled" = disabled,
      "label" = label,
      "hint" = hint,
      "name" = name,
      "autofocus" = autofocus,
      "custom-error" = custom_error,
      "dir" = dir,
      "indicator-offset" = indicator_offset,
      "lang" = lang,
      "max" = max,
      "max-value" = max_value,
      "min" = min,
      "min-value" = min_value,
      "orientation" = orientation,
      "range" = range,
      "readonly" = readonly,
      "required" = required,
      "size" = size,
      "step" = step,
      "tooltip-distance" = tooltip_distance,
      "tooltip-placement" = tooltip_placement,
      "with-markers" = with_markers,
      "with-tooltip" = with_tooltip
    ),
    boolean_names = c(
      "disabled",
      "autofocus",
      "range",
      "readonly",
      "required",
      "with-markers",
      "with-tooltip"
    ),
    boolean_arg_names = c(
      "disabled" = "disabled",
      "autofocus" = "autofocus",
      "range" = "range",
      "readonly" = "readonly",
      "required" = "required",
      "with-markers" = "with_markers",
      "with-tooltip" = "with_tooltip"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-slider", .attrs = attrs),
      children
    )
  )
}
# nolint end

# Generated by tools/generate_components.R. Do not edit by hand.

#' Update a `wa-slider` component
#'
#' Generated update helper for the Web Awesome `wa-slider` component.
#'
#' @param session Shiny session object.
#' @param input_id Input id of the component to update.
#' @param value Optional value to send to the component.
#' @param label Optional label text to send to the component.
#' @param hint Optional hint text to send to the component.
#' @param disabled Optional logical disabled state to send to the component.
#'
#' @return Invisibly returns `NULL`.
#'
#' @rdname wa_slider
#' @export
update_wa_slider <- function(
  session,
  input_id,
  value = NULL,
  label = NULL,
  hint = NULL,
  disabled = NULL
) {
  message <- Filter(
    Negate(is.null),
    list(
      value = value,
      label = label,
      hint = hint,
      disabled = disabled
    )
  )

  if (length(message) == 0L) {
    return(invisible(NULL))
  }

  session$sendInputMessage(input_id, message)
  invisible(NULL)
}
