# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-skeleton` component
#'
#' Generated wrapper for the Web Awesome `wa-skeleton` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param dir Optional Web Awesome attribute.
#' @param effect Determines which effect the skeleton will use. Must be
#' one of `"none"`, `"pulse"`, `"sheen"`. Defaults to `none` when omitted.
#' @param lang Optional Web Awesome attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_skeleton <- function(
  ...,
  id = NULL,
  dir = NULL,
  effect = NULL,
  lang = NULL
) {
  children <- list(...)
  if (!is.null(effect)) {
    effect <- .wa_match_arg(
      effect,
      "effect",
      c(
        "none",
        "pulse",
        "sheen"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "dir" = dir,
      "effect" = effect,
      "lang" = lang
    ),
    boolean_names = character()
  )

  do.call(
    .wa_component,
    c(
      list("wa-skeleton", .attrs = attrs),
      children
    )
  )
}
# nolint end
