# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-tab-group` component
#'
#' Generated wrapper for the Web Awesome `wa-tab-group` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param activation When set to auto, navigating tabs with the arrow keys
#' will instantly show the corresponding tab panel. When set to manual,
#' the tab will receive focus but will not show until the user presses
#' spacebar or enter.
#' @param active Sets the active tab.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param placement The placement of the tabs.
#' @param without_scroll_controls Disables the scroll arrows that appear
#' when tabs overflow.
#' @param nav Used for grouping tabs in the tab group. Must be `<wa-tab>`
#' elements. Note that `<wa-tab>` will set this slot on itself
#' automatically.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_tab_group <- function(
  ...,
  id = NULL,
  activation = NULL,
  active = NULL,
  dir = NULL,
  lang = NULL,
  placement = NULL,
  without_scroll_controls = NULL,
  nav = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(nav, "nav")
    )
  )

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "activation" = activation,
      "active" = active,
      "dir" = dir,
      "lang" = lang,
      "placement" = placement,
      "without-scroll-controls" = without_scroll_controls
    ),
    boolean_names = c("without-scroll-controls")
  )

  do.call(
    .wa_component,
    c(
      list("wa-tab-group", .attrs = attrs),
      children
    )
  )
}
# nolint end
