# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-tab-panel` component
#'
#' Generated wrapper for the Web Awesome `wa-tab-panel` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param name The tab panel's name. Defaults to `` when omitted.
#' @param active When true, the tab panel will be shown. Defaults to
#' `false` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_tab_panel <- function(
  ...,
  id = NULL,
  name = NULL,
  active = NULL,
  dir = NULL,
  lang = NULL
) {
  children <- list(...)



  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "name" = name,
      "active" = active,
      "dir" = dir,
      "lang" = lang
    ),
    boolean_names = c("active"),
    boolean_arg_names = c("active" = "active")
  )

  do.call(
    .wa_component,
    c(
      list("wa-tab-panel", .attrs = attrs),
      children
    )
  )
}
# nolint end
