# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-tree-item` component
#'
#' Generated wrapper for the Web Awesome `wa-tree-item` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param disabled Disables the tree item. Defaults to `false` when
#' omitted.
#' @param dir Optional Web Awesome attribute.
#' @param expanded Expands the tree item. Defaults to `false` when
#' omitted.
#' @param lang Optional Web Awesome attribute.
#' @param lazy Enables lazy loading behavior. Defaults to `false` when
#' omitted.
#' @param selected Draws the tree item in a selected state. Defaults to
#' `false` when omitted.
#' @param collapse_icon The icon to show when the tree item is collapsed.
#' @param expand_icon The icon to show when the tree item is expanded.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_tree_item <- function(
  ...,
  id = NULL,
  disabled = NULL,
  dir = NULL,
  expanded = NULL,
  lang = NULL,
  lazy = NULL,
  selected = NULL,
  collapse_icon = NULL,
  expand_icon = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(collapse_icon, "collapse-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(expand_icon, "expand-icon")
    )
  )



  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "disabled" = disabled,
      "dir" = dir,
      "expanded" = expanded,
      "lang" = lang,
      "lazy" = lazy,
      "selected" = selected
    ),
    boolean_names = c(
      "disabled",
      "expanded",
      "lazy",
      "selected"
    ),
    boolean_arg_names = c(
      "disabled" = "disabled",
      "expanded" = "expanded",
      "lazy" = "lazy",
      "selected" = "selected"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-tree-item", .attrs = attrs),
      children
    )
  )
}
# nolint end
