# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-textarea` component
#'
#' Generated wrapper for the Web Awesome `wa-textarea` component. When
#' used as a Shiny input, `input$<input_id>` reflects the component's
#' current value.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param input_id Shiny input id for the component. This is also used as
#' the rendered DOM `id` attribute.
#' @param class Optional CSS class string.
#' @param style Optional inline CSS style string.
#' @param value The default value of the form control. Primarily used for
#' resetting the form control. This wrapper argument sets the HTML `value`
#' attribute, which maps to the component's `defaultValue` field/property
#' rather than its live `value` property.
#' @param disabled Disables the textarea. Defaults to `false` when
#' omitted.
#' @param label The textarea's label. If you need to display HTML, use the
#' `label` slot instead. Defaults to `` when omitted.
#' @param hint The textarea's hint. If you need to display HTML, use the
#' `hint` slot instead. Defaults to `` when omitted.
#' @param name The name of the textarea, submitted as a name/value pair
#' with form data. Defaults to `null` when omitted.
#' @param appearance The textarea's visual appearance. Must be one of
#' `"filled"`, `"filled-outlined"`, `"outlined"`. Defaults to `outlined`
#' when omitted.
#' @param autocapitalize Controls whether and how text input is
#' automatically capitalized as it is entered by the user. Must be one of
#' `"characters"`, `"none"`, `"off"`, `"on"`, `"sentences"`, `"words"`.
#' @param autocomplete Specifies what permission the browser has to
#' provide assistance in filling out form field values. Refer to this page
#' on MDN for available values.
#' @param autocorrect Indicates whether the browser's autocorrect feature
#' is on or off.
#' @param autofocus Indicates that the input should receive focus on page
#' load.
#' @param custom_error Optional Web Awesome attribute. Defaults to `null`
#' when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param enterkeyhint Used to customize the label or icon of the Enter
#' key on virtual keyboards. Must be one of `"done"`, `"enter"`, `"go"`,
#' `"next"`, `"previous"`, `"search"`, `"send"`.
#' @param inputmode Tells the browser what type of data will be entered by
#' the user, allowing it to display the appropriate virtual keyboard on
#' supportive devices. Must be one of `"decimal"`, `"email"`, `"none"`,
#' `"numeric"`, `"search"`, `"tel"`, `"text"`, `"url"`.
#' @param lang Optional Web Awesome attribute.
#' @param maxlength The maximum length of input that will be considered
#' valid.
#' @param minlength The minimum length of input that will be considered
#' valid.
#' @param placeholder Placeholder text to show as a hint when the input is
#' empty. Defaults to `` when omitted.
#' @param readonly Makes the textarea readonly. Defaults to `false` when
#' omitted.
#' @param required Makes the textarea a required field. Defaults to
#' `false` when omitted.
#' @param resize Controls how the textarea can be resized. Must be one of
#' `"auto"`, `"both"`, `"horizontal"`, `"none"`, `"vertical"`. Defaults to
#' `vertical` when omitted.
#' @param rows The number of rows to display by default. Defaults to `4`
#' when omitted.
#' @param size The textarea's size. Must be one of `"large"`, `"medium"`,
#' `"small"`. Defaults to `medium` when omitted.
#' @param spellcheck Enables spell checking on the textarea. Defaults to
#' `true` when omitted.
#' @param title Optional Web Awesome attribute. Defaults to `` when
#' omitted.
#' @param with_hint Used for SSR. If you're slotting in a `hint` element,
#' make sure to set this to `true`. Defaults to `false` when omitted.
#' @param with_label Used for SSR. If you're slotting in a `label`
#' element, make sure to set this to `true`. Defaults to `false` when
#' omitted.
#' @param hint_slot Text that describes how to use the input.
#' Alternatively, you can use the `hint` attribute.
#' @param label_slot The textarea's label. Alternatively, you can use the
#' `label` attribute.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_textarea <- function(
  input_id,
  ...,
  class = NULL,
  style = NULL,
  value = NULL,
  disabled = NULL,
  label = NULL,
  hint = NULL,
  name = NULL,
  appearance = NULL,
  autocapitalize = NULL,
  autocomplete = NULL,
  autocorrect = NULL,
  autofocus = NULL,
  custom_error = NULL,
  dir = NULL,
  enterkeyhint = NULL,
  inputmode = NULL,
  lang = NULL,
  maxlength = NULL,
  minlength = NULL,
  placeholder = NULL,
  readonly = NULL,
  required = NULL,
  resize = NULL,
  rows = NULL,
  size = NULL,
  spellcheck = NULL,
  title = NULL,
  with_hint = NULL,
  with_label = NULL,
  hint_slot = NULL,
  label_slot = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(hint_slot, "hint")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(label_slot, "label")
    )
  )

  if (!is.null(appearance)) {
    appearance <- .wa_match_arg(
      appearance,
      "appearance",
      c(
        "filled",
        "filled-outlined",
        "outlined"
      )
    )
  }

  if (!is.null(autocapitalize)) {
    autocapitalize <- .wa_match_arg(
      autocapitalize,
      "autocapitalize",
      c(
        "characters",
        "none",
        "off",
        "on",
        "sentences",
        "words"
      )
    )
  }

  if (!is.null(enterkeyhint)) {
    enterkeyhint <- .wa_match_arg(
      enterkeyhint,
      "enterkeyhint",
      c(
        "done",
        "enter",
        "go",
        "next",
        "previous",
        "search",
        "send"
      )
    )
  }

  if (!is.null(inputmode)) {
    inputmode <- .wa_match_arg(
      inputmode,
      "inputmode",
      c(
        "decimal",
        "email",
        "none",
        "numeric",
        "search",
        "tel",
        "text",
        "url"
      )
    )
  }

  if (!is.null(resize)) {
    resize <- .wa_match_arg(
      resize,
      "resize",
      c(
        "auto",
        "both",
        "horizontal",
        "none",
        "vertical"
      )
    )
  }

  if (!is.null(size)) {
    size <- .wa_match_arg(
      size,
      "size",
      c(
        "large",
        "medium",
        "small"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = input_id,
      "class" = class,
      "style" = style,
      "value" = value,
      "disabled" = disabled,
      "label" = label,
      "hint" = hint,
      "name" = name,
      "appearance" = appearance,
      "autocapitalize" = autocapitalize,
      "autocomplete" = autocomplete,
      "autocorrect" = autocorrect,
      "autofocus" = autofocus,
      "custom-error" = custom_error,
      "dir" = dir,
      "enterkeyhint" = enterkeyhint,
      "inputmode" = inputmode,
      "lang" = lang,
      "maxlength" = maxlength,
      "minlength" = minlength,
      "placeholder" = placeholder,
      "readonly" = readonly,
      "required" = required,
      "resize" = resize,
      "rows" = rows,
      "size" = size,
      "spellcheck" = spellcheck,
      "title" = title,
      "with-hint" = with_hint,
      "with-label" = with_label
    ),
    boolean_names = c(
      "disabled",
      "autofocus",
      "readonly",
      "required",
      "spellcheck",
      "with-hint",
      "with-label"
    ),
    boolean_arg_names = c(
      "disabled" = "disabled",
      "autofocus" = "autofocus",
      "readonly" = "readonly",
      "required" = "required",
      "spellcheck" = "spellcheck",
      "with-hint" = "with_hint",
      "with-label" = "with_label"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-textarea", .attrs = attrs),
      children
    )
  )
}
# nolint end

# Generated by tools/generate_components.R. Do not edit by hand.

#' Update a `wa-textarea` component
#'
#' Generated update helper for the Web Awesome `wa-textarea` component.
#'
#' @param session Shiny session object.
#' @param input_id Input id of the component to update.
#' @param value Optional value to send to the component.
#' @param label Optional label text to send to the component.
#' @param hint Optional hint text to send to the component.
#' @param disabled Optional logical disabled state to send to the component.
#'
#' @return Invisibly returns `NULL`.
#'
#' @rdname wa_textarea
#' @export
update_wa_textarea <- function(
  session,
  input_id,
  value = NULL,
  label = NULL,
  hint = NULL,
  disabled = NULL
) {
  message <- Filter(
    Negate(is.null),
    list(
      value = value,
      label = label,
      hint = hint,
      disabled = disabled
    )
  )

  if (length(message) == 0L) {
    return(invisible(NULL))
  }

  session$sendInputMessage(input_id, message)
  invisible(NULL)
}
