# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-tab` component
#'
#' Generated wrapper for the Web Awesome `wa-tab` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param disabled Disables the tab and prevents selection. Defaults to
#' `false` when omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param panel The name of the tab panel this tab is associated with. The
#' panel must be located in the same tab group. Defaults to `` when
#' omitted.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_tab <- function(
  ...,
  id = NULL,
  disabled = NULL,
  dir = NULL,
  lang = NULL,
  panel = NULL
) {
  children <- list(...)


  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "disabled" = disabled,
      "dir" = dir,
      "lang" = lang,
      "panel" = panel
    ),
    boolean_names = c("disabled"),
    boolean_arg_names = c("disabled" = "disabled")
  )

  do.call(
    .wa_component,
    c(
      list("wa-tab", .attrs = attrs),
      children
    )
  )
}
# nolint end
