# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-tooltip` component
#'
#' Generated wrapper for the Web Awesome `wa-tooltip` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param disabled Disables the tooltip so it won't show when triggered.
#' @param dir Optional Web Awesome attribute.
#' @param distance The distance in pixels from which to offset the tooltip
#' away from its target.
#' @param for Optional Web Awesome attribute.
#' @param hide_delay The amount of time to wait before hiding the tooltip
#' when the user mouses out.
#' @param lang Optional Web Awesome attribute.
#' @param open Indicates whether or not the tooltip is open. You can use
#' this in lieu of the show/hide methods.
#' @param placement The preferred placement of the tooltip. Note that the
#' actual placement may vary as needed to keep the tooltip inside of the
#' viewport.
#' @param show_delay The amount of time to wait before showing the tooltip
#' when the user mouses in.
#' @param skidding The distance in pixels from which to offset the tooltip
#' along its target.
#' @param trigger Controls how the tooltip is activated. Possible options
#' include `click`, `hover`, `focus`, and `manual`. Multiple options can
#' be passed by separating them with a space. When manual is used, the
#' tooltip must be activated programmatically.
#' @param without_arrow Removes the arrow from the tooltip.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_tooltip <- function(
  ...,
  id = NULL,
  disabled = NULL,
  dir = NULL,
  distance = NULL,
  `for` = NULL,
  hide_delay = NULL,
  lang = NULL,
  open = NULL,
  placement = NULL,
  show_delay = NULL,
  skidding = NULL,
  trigger = NULL,
  without_arrow = NULL
) {
  children <- list(...)

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "disabled" = disabled,
      "dir" = dir,
      "distance" = distance,
      "for" = `for`,
      "hide-delay" = hide_delay,
      "lang" = lang,
      "open" = open,
      "placement" = placement,
      "show-delay" = show_delay,
      "skidding" = skidding,
      "trigger" = trigger,
      "without-arrow" = without_arrow
    ),
    boolean_names = c("disabled", "open", "without-arrow")
  )

  do.call(
    .wa_component,
    c(
      list("wa-tooltip", .attrs = attrs),
      children
    )
  )
}
# nolint end
