# Generated by tools/generate_components.R. Do not edit by hand.
# nolint start: object_usage_linter.

#' Create a `wa-zoomable-frame` component
#'
#' Generated wrapper for the Web Awesome `wa-zoomable-frame` component.
#' Generated from Web Awesome metadata.
#'
#' @param ... Child content for the component's default slot.
#' @param id Optional DOM id attribute for HTML, CSS, and JS targeting.
#' @param allowfullscreen Allows fullscreen mode. Defaults to `false` when
#' omitted.
#' @param dir Optional Web Awesome attribute.
#' @param lang Optional Web Awesome attribute.
#' @param loading Controls iframe loading behavior. Must be one of
#' `"eager"`, `"lazy"`. Defaults to `eager` when omitted.
#' @param referrerpolicy Controls referrer information.
#' @param sandbox Security restrictions for the iframe.
#' @param src The URL of the content to display.
#' @param srcdoc Inline HTML to display.
#' @param without_controls Removes the zoom controls. Defaults to `false`
#' when omitted.
#' @param without_interaction Disables interaction when present. Defaults
#' to `false` when omitted.
#' @param zoom The current zoom of the frame, e.g. 0 = 0% and 1 = 100%.
#' Defaults to `1` when omitted.
#' @param zoom_levels The zoom levels to step through when using zoom
#' controls. This does not restrict programmatic changes to the zoom.
#' Defaults to `25% 50% 75% 100% 125% 150% 175% 200%` when omitted.
#' @param zoom_in_icon The slot that contains the zoom in icon.
#' @param zoom_out_icon The slot that contains the zoom out icon.
#'
#' @return An HTML tag for the component.
#'
#' @export
wa_zoomable_frame <- function(
  ...,
  id = NULL,
  allowfullscreen = NULL,
  dir = NULL,
  lang = NULL,
  loading = NULL,
  referrerpolicy = NULL,
  sandbox = NULL,
  src = NULL,
  srcdoc = NULL,
  without_controls = NULL,
  without_interaction = NULL,
  zoom = NULL,
  zoom_levels = NULL,
  zoom_in_icon = NULL,
  zoom_out_icon = NULL
) {
  children <- list(...)
  children <- c(
    children,
    list(
      .wa_slot(zoom_in_icon, "zoom-in-icon")
    )
  )
  children <- c(
    children,
    list(
      .wa_slot(zoom_out_icon, "zoom-out-icon")
    )
  )
  if (!is.null(loading)) {
    loading <- .wa_match_arg(
      loading,
      "loading",
      c(
        "eager",
        "lazy"
      )
    )
  }

  attrs <- .wa_normalize_attrs(
    list(
      "id" = id,
      "allowfullscreen" = allowfullscreen,
      "dir" = dir,
      "lang" = lang,
      "loading" = loading,
      "referrerpolicy" = referrerpolicy,
      "sandbox" = sandbox,
      "src" = src,
      "srcdoc" = srcdoc,
      "without-controls" = without_controls,
      "without-interaction" = without_interaction,
      "zoom" = zoom,
      "zoom-levels" = zoom_levels
    ),
    boolean_names = c(
      "allowfullscreen",
      "without-controls",
      "without-interaction"
    ),
    boolean_arg_names = c(
      "allowfullscreen" = "allowfullscreen",
      "without-controls" = "without_controls",
      "without-interaction" = "without_interaction"
    )
  )

  do.call(
    .wa_component,
    c(
      list("wa-zoomable-frame", .attrs = attrs),
      children
    )
  )
}
# nolint end
